/**
 * Smart Pantry - Free Master Recipe Database (185+ Real Recipes)
 * 100% Free for all users. Zero paywalls.
 */

const MASTER_RECIPES = [
  // ==================== BREAKFAST (1-20) ====================
  {
    id: "rec_1",
    name: "Masala Dosa",
    category: "Breakfast",
    categories: ["Breakfast", "South Indian", "Vegetarian", "Rice", "Budget Meals"],
    cuisine: "South Indian",
    emoji: "🥞",
    image: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=600&q=80",
    description: "Crispy fermented rice and lentil crepe stuffed with spiced potato masala and served with chutneys.",
    ingredients: ["Rice", "Urad Dal", "Potato", "Onion", "Green Chili", "Mustard Seeds", "Curry Leaves", "Turmeric", "Oil", "Salt"],
    requiredIngredients: ["Rice", "Potato", "Onion"],
    optionalIngredients: ["Curry Leaves", "Mustard Seeds", "Green Chili"],
    prepTime: "15 mins",
    cookTime: "20 mins",
    totalMinutes: 35,
    difficulty: "Medium",
    servings: 4,
    isVegetarian: true,
    isVegan: true,
    nutrition: { calories: 320, protein: "8g", carbs: "56g", fat: "7g" },
    instructions: [
      "Soak and grind rice and urad dal, then ferment batter overnight.",
      "Boil and mash potatoes. Sauté onions, green chilies, mustard seeds, turmeric, and curry leaves.",
      "Mix spiced onion mixture with mashed potatoes to form the filling.",
      "Pour batter on a hot tawa, spread thinly into a circle, and drizzle oil.",
      "Place potato masala in the center, fold when golden brown and crispy, and serve hot."
    ]
  },
  {
    id: "rec_2",
    name: "Plain Dosa",
    category: "Breakfast",
    categories: ["Breakfast", "South Indian", "Vegetarian", "Vegan", "Budget Meals", "Quick Meals"],
    cuisine: "South Indian",
    emoji: "🥞",
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80",
    description: "Classic paper-thin golden crispy crepe made with naturally fermented rice batter.",
    ingredients: ["Rice", "Urad Dal", "Fenugreek Seeds", "Oil", "Salt"],
    requiredIngredients: ["Rice", "Oil"],
    optionalIngredients: ["Fenugreek Seeds", "Salt"],
    prepTime: "5 mins",
    cookTime: "10 mins",
    totalMinutes: 15,
    difficulty: "Easy",
    servings: 3,
    isVegetarian: true,
    isVegan: true,
    nutrition: { calories: 180, protein: "5g", carbs: "34g", fat: "3g" },
    instructions: [
      "Prepare smooth fermented rice and urad dal batter.",
      "Heat a cast iron pan and grease with a drop of oil.",
      "Pour a ladle of batter and swirl quickly from center outwards.",
      "Cook until golden and crisp, flip gently or fold and serve with sambar."
    ]
  },
  {
    id: "rec_3",
    name: "Idli",
    category: "Breakfast",
    categories: ["Breakfast", "South Indian", "Vegetarian", "Healthy", "Budget Meals"],
    cuisine: "South Indian",
    emoji: "⚪",
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80",
    description: "Soft, fluffy steamed savory rice cakes, wholesome and easy to digest.",
    ingredients: ["Rice", "Urad Dal", "Salt", "Water"],
    requiredIngredients: ["Rice", "Salt"],
    optionalIngredients: ["Urad Dal"],
    prepTime: "10 mins",
    cookTime: "12 mins",
    totalMinutes: 22,
    difficulty: "Easy",
    servings: 4,
    isVegetarian: true,
    isVegan: true,
    nutrition: { calories: 140, protein: "4g", carbs: "28g", fat: "1g" },
    instructions: [
      "Grease idli plates with a light coating of oil.",
      "Pour fermented batter into each mold.",
      "Steam in a steamer for 10-12 minutes on medium-high heat.",
      "Rest for 2 minutes, unmold with a wet spoon, and serve warm."
    ]
  },
  {
    id: "rec_4",
    name: "Sambar Idli",
    category: "Breakfast",
    categories: ["Breakfast", "South Indian", "Vegetarian", "Healthy"],
    cuisine: "South Indian",
    emoji: "🍲",
    image: "https://images.unsplash.com/photo-1610057099431-d73a1c9d2f2f?auto=format&fit=crop&w=600&q=80",
    description: "Soft steamed idlis dipped in piping hot, aromatic lentil and vegetable sambar.",
    ingredients: ["Rice", "Toor Dal", "Tomato", "Onion", "Drumstick", "Carrot", "Sambar Powder", "Curry Leaves", "Coriander", "Salt"],
    requiredIngredients: ["Rice", "Tomato", "Onion"],
    optionalIngredients: ["Carrot", "Curry Leaves", "Coriander"],
    prepTime: "15 mins",
    cookTime: "25 mins",
    totalMinutes: 40,
    difficulty: "Medium",
    servings: 3,
    isVegetarian: true,
    isVegan: true,
    nutrition: { calories: 260, protein: "9g", carbs: "48g", fat: "3g" },
    instructions: [
      "Cook toor dal with tomatoes, onions, carrots, and turmeric until soft.",
      "Add sambar powder, tamarind extract, and simmer for 10 minutes.",
      "Temper mustard seeds, curry leaves, and pour over sambar.",
      "Immerse fresh steamed idlis in hot sambar and garnish with coriander."
    ]
  },
  {
    id: "rec_5",
    name: "Appam",
    category: "Breakfast",
    categories: ["Breakfast", "Kerala", "South Indian", "Vegetarian", "Vegan", "Budget Meals"],
    cuisine: "Kerala",
    emoji: "🍳",
    image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80",
    description: "Traditional Kerala bowl-shaped fermented rice pancake with a soft spongy center and crispy lace edges.",
    ingredients: ["Rice", "Coconut", "Yeast", "Sugar", "Salt", "Water"],
    requiredIngredients: ["Rice", "Coconut", "Sugar"],
    optionalIngredients: ["Yeast", "Salt"],
    prepTime: "10 mins",
    cookTime: "15 mins",
    totalMinutes: 25,
    difficulty: "Easy",
    servings: 4,
    isVegetarian: true,
    isVegan: true,
    nutrition: { calories: 190, protein: "3g", carbs: "38g", fat: "3g" },
    instructions: [
      "Grind soaked raw rice with grated coconut, yeast, sugar, and water into a smooth batter.",
      "Ferment for 6-8 hours until risen and bubbly.",
      "Pour a ladle of batter into an appachatti, swirl around to form lacy edges.",
      "Cover and steam for 2 minutes until center is fluffy and edges are golden."
    ]
  },
  {
    id: "rec_6",
    name: "Egg Appam",
    category: "Breakfast",
    categories: ["Breakfast", "Kerala", "Egg", "Quick Meals", "High Protein"],
    cuisine: "Kerala",
    emoji: "🍳",
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=600&q=80",
    description: "Kerala lacy appam with a fresh egg dropped into the center and seasoned with black pepper.",
    ingredients: ["Rice", "Coconut", "Egg", "Black Pepper", "Salt", "Oil"],
    requiredIngredients: ["Rice", "Egg", "Black Pepper"],
    optionalIngredients: ["Coconut", "Salt"],
    prepTime: "10 mins",
    cookTime: "15 mins",
    totalMinutes: 25,
    difficulty: "Easy",
    servings: 2,
    isVegetarian: false,
    isVegan: false,
    nutrition: { calories: 270, protein: "10g", carbs: "38g", fat: "8g" },
    instructions: [
      "Pour appam batter into hot appam pan and swirl.",
      "Crack a fresh egg into the center depression.",
      "Sprinkle salt and crushed black pepper on top.",
      "Cover and cook on low heat until egg white sets and yolk is soft."
    ]
  },
  {
    id: "rec_7",
    name: "Vegetable Upma",
    category: "Breakfast",
    categories: ["Breakfast", "South Indian", "Vegetarian", "Healthy", "Quick Meals", "Budget Meals"],
    cuisine: "South Indian",
    emoji: "🥣",
    image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80",
    description: "Savory semolina porridge tossed with carrots, green peas, onions, and tempered spices.",
    ingredients: ["Rava", "Onion", "Carrot", "Green Peas", "Ginger", "Green Chili", "Mustard Seeds", "Curry Leaves", "Oil", "Salt"],
    requiredIngredients: ["Rava", "Onion", "Carrot"],
    optionalIngredients: ["Green Peas", "Ginger", "Curry Leaves"],
    prepTime: "10 mins",
    cookTime: "15 mins",
    totalMinutes: 25,
    difficulty: "Easy",
    servings: 3,
    isVegetarian: true,
    isVegan: true,
    nutrition: { calories: 230, protein: "6g", carbs: "42g", fat: "5g" },
    instructions: [
      "Dry roast rava/semolina until aromatic and set aside.",
      "Heat oil, temper mustard seeds, curry leaves, ginger, and green chilies.",
      "Sauté chopped onions, carrots, and green peas.",
      "Add water and salt, bring to a rolling boil, then gradually whisk in roasted rava.",
      "Cover and simmer on low for 3 minutes until fluffy."
    ]
  },
  {
    id: "rec_8",
    name: "Rava Upma",
    category: "Breakfast",
    categories: ["Breakfast", "South Indian", "Vegetarian", "Quick Meals", "Budget Meals"],
    cuisine: "South Indian",
    emoji: "🥣",
    image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80",
    description: "Classic quick savory roasted semolina breakfast tempered with mustard and ginger.",
    ingredients: ["Rava", "Onion", "Ginger", "Green Chili", "Mustard Seeds", "Oil", "Salt", "Water"],
    requiredIngredients: ["Rava", "Onion", "Oil"],
    optionalIngredients: ["Ginger", "Green Chili", "Mustard Seeds"],
    prepTime: "5 mins",
    cookTime: "12 mins",
    totalMinutes: 17,
    difficulty: "Easy",
    servings: 2,
    isVegetarian: true,
    isVegan: true,
    nutrition: { calories: 210, protein: "5g", carbs: "39g", fat: "4g" },
    instructions: [
      "Roast semolina on medium heat until warm and light.",
      "Sauté chopped onions, ginger, and chilies in oil with mustard seeds.",
      "Add 2.5 cups of water and salt; bring to a boil.",
      "Slowly pour in semolina while stirring continuously to prevent lumps.",
      "Cover and steam for 2 minutes, then fluff with a spoon."
    ]
  },
  {
    id: "rec_9",
    name: "Poha",
    category: "Breakfast",
    categories: ["Breakfast", "Indian", "Vegetarian", "Healthy", "Quick Meals", "Budget Meals"],
    cuisine: "North Indian",
    emoji: "🍚",
    image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80",
    description: "Flattened rice flakes tempered with onions, turmeric, mustard seeds, and crunchy roasted peanuts.",
    ingredients: ["Poha", "Onion", "Peanuts", "Green Chili", "Turmeric", "Mustard Seeds", "Lemon Juice", "Coriander", "Oil", "Salt"],
    requiredIngredients: ["Poha", "Onion", "Turmeric"],
    optionalIngredients: ["Peanuts", "Lemon Juice", "Coriander"],
    prepTime: "5 mins",
    cookTime: "10 mins",
    totalMinutes: 15,
    difficulty: "Easy",
    servings: 2,
    isVegetarian: true,
    isVegan: true,
    nutrition: { calories: 240, protein: "6g", carbs: "44g", fat: "6g" },
    instructions: [
      "Rinse flattened rice (poha) in a colander and drain excess water.",
      "Heat oil in a pan, fry peanuts until crunchy, then add mustard seeds and green chilies.",
      "Add sliced onions and sauté until translucent. Stir in turmeric and salt.",
      "Add rinsed poha, toss gently to coat with spices, and cover for 2 minutes.",
      "Squeeze fresh lemon juice, garnish with coriander, and serve."
    ]
  },
  {
    id: "rec_10",
    name: "Vegetable Poha",
    category: "Breakfast",
    categories: ["Breakfast", "Indian", "Vegetarian", "Healthy", "Quick Meals"],
    cuisine: "Indian",
    emoji: "🍚",
    image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80",
    description: "Nutritious flattened rice loaded with diced carrots, potatoes, green peas, and fresh herbs.",
    ingredients: ["Poha", "Potato", "Carrot", "Green Peas", "Onion", "Turmeric", "Mustard Seeds", "Lemon Juice", "Oil", "Salt"],
    requiredIngredients: ["Poha", "Potato", "Carrot", "Onion"],
    optionalIngredients: ["Green Peas", "Lemon Juice", "Mustard Seeds"],
    prepTime: "10 mins",
    cookTime: "15 mins",
    totalMinutes: 25,
    difficulty: "Easy",
    servings: 3,
    isVegetarian: true,
    isVegan: true,
    nutrition: { calories: 270, protein: "7g", carbs: "52g", fat: "5g" },
    instructions: [
      "Rinse poha and let rest.",
      "Sauté diced potatoes and carrots in oil until tender.",
      "Add onions, green peas, turmeric, and salt.",
      "Toss in poha, mix evenly, cover for 3 minutes on low heat, and finish with lemon."
    ]
  },
  {
    id: "rec_11",
    name: "Puttu & Kadala Curry",
    category: "Breakfast",
    categories: ["Breakfast", "Kerala", "South Indian", "Vegetarian", "High Protein"],
    cuisine: "Kerala",
    emoji: "🥥",
    image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80",
    description: "Iconic Kerala breakfast: Steamed rice flour cylinders layered with grated coconut served with spicy black chickpea curry.",
    ingredients: ["Rice Flour", "Grated Coconut", "Black Chickpeas", "Onion", "Tomato", "Ginger", "Garlic", "Coconut Milk", "Curry Powder", "Oil", "Salt"],
    requiredIngredients: ["Rice Flour", "Grated Coconut", "Black Chickpeas", "Onion", "Tomato"],
    optionalIngredients: ["Coconut Milk", "Ginger", "Garlic"],
    prepTime: "20 mins",
    cookTime: "30 mins",
    totalMinutes: 50,
    difficulty: "Medium",
    servings: 4,
    isVegetarian: true,
    isVegan: true,
    nutrition: { calories: 420, protein: "14g", carbs: "72g", fat: "9g" },
    instructions: [
      "Pressure cook soaked black chickpeas with onions, tomatoes, ginger, and curry spices.",
      "Simmer curry with coconut milk until gravy is thick.",
      "Dampen rice flour with salted warm water until crumbly.",
      "Layer puttu maker with coconut and rice flour alternately, steam for 5 minutes.",
      "Push out hot steamed puttu and serve with flavorful kadala curry."
    ]
  },
  {
    id: "rec_12",
    name: "Bread Omelette",
    category: "Breakfast",
    categories: ["Breakfast", "Egg", "Quick Meals", "Snacks", "High Protein", "Budget Meals"],
    cuisine: "Indian",
    emoji: "🥪",
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=600&q=80",
    description: "Fluffy street-style spiced egg omelette folded around golden toasted bread slices.",
    ingredients: ["Bread", "Egg", "Onion", "Green Chili", "Tomato", "Black Pepper", "Butter", "Salt"],
    requiredIngredients: ["Bread", "Egg", "Onion"],
    optionalIngredients: ["Tomato", "Green Chili", "Butter"],
    prepTime: "5 mins",
    cookTime: "8 mins",
    totalMinutes: 13,
    difficulty: "Easy",
    servings: 1,
    isVegetarian: false,
    isVegan: false,
    nutrition: { calories: 310, protein: "16g", carbs: "28g", fat: "14g" },
    instructions: [
      "Whisk eggs with finely chopped onions, tomatoes, green chilies, pepper, and salt.",
      "Melt butter in a pan and pour the egg mixture.",
      "Place two bread slices on top, flip them over to coat with egg.",
      "Once bottom is cooked, flip the entire omelette and fold excess egg over bread slices.",
      "Toast until bread is crisp and golden."
    ]
  },
  {
    id: "rec_13",
    name: "French Toast",
    category: "Breakfast",
    categories: ["Breakfast", "Desserts", "Quick Meals", "Egg", "Budget Meals"],
    cuisine: "International",
    emoji: "🍞",
    image: "https://images.unsplash.com/photo-1484723091739-30a097e8f929?auto=format&fit=crop&w=600&q=80",
    description: "Golden pan-fried bread slices soaked in a rich vanilla cinnamon egg custard.",
    ingredients: ["Bread", "Egg", "Milk", "Sugar", "Cinnamon", "Butter", "Honey"],
    requiredIngredients: ["Bread", "Egg", "Milk", "Sugar"],
    optionalIngredients: ["Cinnamon", "Honey"],
    prepTime: "5 mins",
    cookTime: "8 mins",
    totalMinutes: 13,
    difficulty: "Easy",
    servings: 2,
    isVegetarian: false,
    isVegan: false,
    nutrition: { calories: 290, protein: "11g", carbs: "36g", fat: "11g" },
    instructions: [
      "Whisk eggs, milk, sugar, and cinnamon in a shallow bowl.",
      "Dip bread slices on both sides to absorb the custard.",
      "Melt butter in a skillet over medium heat.",
      "Cook bread slices for 2-3 minutes per side until golden brown.",
      "Drizzle with honey or maple syrup and serve warm."
    ]
  },
  {
    id: "rec_14",
    name: "Scrambled Eggs",
    category: "Breakfast",
    categories: ["Breakfast", "Egg", "Quick Meals", "Healthy", "High Protein"],
    cuisine: "International",
    emoji: "🍳",
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=600&q=80",
    description: "Silky, soft, and buttery scrambled eggs seasoned simply with black pepper and herbs.",
    ingredients: ["Egg", "Milk", "Butter", "Black Pepper", "Salt", "Chives"],
    requiredIngredients: ["Egg", "Butter", "Salt"],
    optionalIngredients: ["Milk", "Black Pepper", "Chives"],
    prepTime: "3 mins",
    cookTime: "5 mins",
    totalMinutes: 8,
    difficulty: "Easy",
    servings: 2,
    isVegetarian: false,
    isVegan: false,
    nutrition: { calories: 190, protein: "13g", carbs: "2g", fat: "14g" },
    instructions: [
      "Beat eggs with milk and a pinch of salt until well blended.",
      "Melt butter in a non-stick skillet on low heat.",
      "Pour in eggs and gently push soft curds with a spatula as they form.",
      "Remove from heat while still slightly glossy and finish with black pepper."
    ]
  },
  {
    id: "rec_15",
    name: "Boiled Egg Toast",
    category: "Breakfast",
    categories: ["Breakfast", "Egg", "Healthy", "Quick Meals", "High Protein"],
    cuisine: "International",
    emoji: "🥪",
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=600&q=80",
    description: "Crunchy toasted artisan bread topped with sliced boiled eggs, olive oil, and herbs.",
    ingredients: ["Bread", "Egg", "Black Pepper", "Butter", "Salt", "Chili Flakes"],
    requiredIngredients: ["Bread", "Egg", "Black Pepper"],
    optionalIngredients: ["Butter", "Chili Flakes"],
    prepTime: "5 mins",
    cookTime: "10 mins",
    totalMinutes: 15,
    difficulty: "Easy",
    servings: 1,
    isVegetarian: false,
    isVegan: false,
    nutrition: { calories: 230, protein: "14g", carbs: "24g", fat: "8g" },
    instructions: [
      "Boil eggs for 8 minutes, peel, and slice evenly.",
      "Toast bread slices until golden and spread a touch of butter.",
      "Layer sliced eggs over toast, season with sea salt, crushed pepper, and chili flakes."
    ]
  },
  {
    id: "rec_16",
    name: "Vegetable Sandwich",
    category: "Breakfast",
    categories: ["Breakfast", "Snacks", "Vegetarian", "Healthy", "Quick Meals", "Budget Meals"],
    cuisine: "Indian",
    emoji: "🥪",
    image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=600&q=80",
    description: "Crispy grilled sandwich packed with sliced cucumber, tomato, onion, and mint chutney.",
    ingredients: ["Bread", "Cucumber", "Tomato", "Onion", "Butter", "Chaat Masala", "Mint Chutney", "Salt"],
    requiredIngredients: ["Bread", "Tomato", "Cucumber", "Onion"],
    optionalIngredients: ["Butter", "Chaat Masala", "Mint Chutney"],
    prepTime: "8 mins",
    cookTime: "5 mins",
    totalMinutes: 13,
    difficulty: "Easy",
    servings: 2,
    isVegetarian: true,
    isVegan: false,
    nutrition: { calories: 220, protein: "6g", carbs: "38g", fat: "6g" },
    instructions: [
      "Spread butter and green mint chutney on bread slices.",
      "Layer thin slices of cucumber, tomato, and onion.",
      "Sprinkle chaat masala and salt.",
      "Cover with second bread slice, toast on a pan until golden and crunchy."
    ]
  },
  {
    id: "rec_17",
    name: "Egg Sandwich",
    category: "Breakfast",
    categories: ["Breakfast", "Egg", "Quick Meals", "High Protein", "Snacks"],
    cuisine: "International",
    emoji: "🥪",
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=600&q=80",
    description: "Creamy egg salad with cracked black pepper and fresh greens layered in toasted bread.",
    ingredients: ["Bread", "Egg", "Mayonnaise", "Black Pepper", "Mustard", "Salt"],
    requiredIngredients: ["Bread", "Egg", "Black Pepper"],
    optionalIngredients: ["Mayonnaise", "Mustard"],
    prepTime: "8 mins",
    cookTime: "10 mins",
    totalMinutes: 18,
    difficulty: "Easy",
    servings: 2,
    isVegetarian: false,
    isVegan: false,
    nutrition: { calories: 290, protein: "15g", carbs: "26g", fat: "13g" },
    instructions: [
      "Hard boil eggs, cool, peel, and chop into small cubes.",
      "Mix with mayonnaise, black pepper, a touch of mustard, and salt.",
      "Spread generously between slices of toasted bread."
    ]
  },
  {
    id: "rec_18",
    name: "Masala Omelette",
    category: "Breakfast",
    categories: ["Breakfast", "Egg", "Quick Meals", "High Protein", "South Indian"],
    cuisine: "Indian",
    emoji: "🍳",
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=600&q=80",
    description: "Spicy Indian-style fluffy omelette packed with onions, tomatoes, chilies, and coriander.",
    ingredients: ["Egg", "Onion", "Tomato", "Green Chili", "Coriander", "Turmeric", "Oil", "Salt"],
    requiredIngredients: ["Egg", "Onion", "Tomato"],
    optionalIngredients: ["Green Chili", "Coriander", "Turmeric"],
    prepTime: "5 mins",
    cookTime: "5 mins",
    totalMinutes: 10,
    difficulty: "Easy",
    servings: 1,
    isVegetarian: false,
    isVegan: false,
    nutrition: { calories: 210, protein: "14g", carbs: "4g", fat: "15g" },
    instructions: [
      "Whisk 2 eggs vigorously with chopped onions, tomatoes, chilies, turmeric, and salt.",
      "Heat oil in a pan on medium flame and pour the egg mixture.",
      "Cook for 2 minutes until bottom sets, flip carefully, cook for another minute, and serve hot."
    ]
  },
  {
    id: "rec_19",
    name: "Pancakes",
    category: "Breakfast",
    categories: ["Breakfast", "Desserts", "Quick Meals", "Vegetarian"],
    cuisine: "International",
    emoji: "🥞",
    image: "https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=600&q=80",
    description: "Fluffy golden buttermilk pancakes served with melted butter and sweet honey.",
    ingredients: ["Flour", "Milk", "Egg", "Sugar", "Baking Powder", "Butter", "Honey", "Salt"],
    requiredIngredients: ["Flour", "Milk", "Sugar"],
    optionalIngredients: ["Egg", "Baking Powder", "Honey"],
    prepTime: "8 mins",
    cookTime: "10 mins",
    totalMinutes: 18,
    difficulty: "Easy",
    servings: 3,
    isVegetarian: false,
    isVegan: false,
    nutrition: { calories: 310, protein: "8g", carbs: "48g", fat: "10g" },
    instructions: [
      "Whisk dry ingredients (flour, sugar, baking powder, salt) together.",
      "In another bowl, whisk milk, egg, and melted butter.",
      "Combine wet and dry ingredients gently without overmixing.",
      "Cook ladles of batter on a hot greased griddle until bubbles pop, flip and cook till golden."
    ]
  },
  {
    id: "rec_20",
    name: "Oats Porridge",
    category: "Breakfast",
    categories: ["Breakfast", "Healthy", "Vegetarian", "Quick Meals", "Budget Meals"],
    cuisine: "International",
    emoji: "🥣",
    image: "https://images.unsplash.com/photo-1584776296944-ab6fb57b0bdd?auto=format&fit=crop&w=600&q=80",
    description: "Creamy, wholesome rolled oats cooked in milk and topped with fresh sliced fruits and honey.",
    ingredients: ["Oats", "Milk", "Honey", "Apple", "Banana", "Cinnamon"],
    requiredIngredients: ["Oats", "Milk"],
    optionalIngredients: ["Honey", "Apple", "Banana", "Cinnamon"],
    prepTime: "3 mins",
    cookTime: "7 mins",
    totalMinutes: 10,
    difficulty: "Easy",
    servings: 1,
    isVegetarian: true,
    isVegan: false,
    nutrition: { calories: 260, protein: "10g", carbs: "45g", fat: "5g" },
    instructions: [
      "Add oats and milk to a saucepan over medium heat.",
      "Simmer for 5-7 minutes while stirring until thick and creamy.",
      "Pour into a bowl, sweeten with honey, and top with fresh apple and banana slices."
    ]
  },

  // ==================== RICE DISHES (21-38) ====================
  {
    id: "rec_21",
    name: "Chicken Fried Rice",
    category: "Rice",
    categories: ["Rice", "Chicken", "Lunch", "Dinner", "Quick Meals", "High Protein"],
    cuisine: "International",
    emoji: "🍚",
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80",
    description: "Wok-tossed fragrant rice with tender chicken breast pieces, vegetables, egg, and savory soy sauce.",
    ingredients: ["Rice", "Chicken", "Egg", "Onion", "Carrot", "Garlic", "Soy Sauce", "Spring Onion", "Oil", "Black Pepper"],
    requiredIngredients: ["Rice", "Chicken", "Egg", "Onion", "Carrot"],
    optionalIngredients: ["Garlic", "Soy Sauce", "Spring Onion", "Black Pepper"],
    prepTime: "10 mins",
    cookTime: "15 mins",
    totalMinutes: 25,
    difficulty: "Easy",
    servings: 3,
    isVegetarian: false,
    isVegan: false,
    nutrition: { calories: 480, protein: "32g", carbs: "58g", fat: "14g" },
    instructions: [
      "Cook chicken pieces in a hot wok with garlic and oil until tender.",
      "Push chicken aside, scramble the egg in the center.",
      "Add finely diced carrots and onions; stir fry on high heat for 2 minutes.",
      "Add cold cooked rice, soy sauce, and black pepper.",
      "Toss vigorously on high heat for 3 minutes and garnish with spring onions."
    ]
  },
  {
    id: "rec_22",
    name: "Vegetable Fried Rice",
    category: "Rice",
    categories: ["Rice", "Vegetarian", "Vegan", "Lunch", "Dinner", "Quick Meals", "Budget Meals"],
    cuisine: "International",
    emoji: "🍚",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=600&q=80",
    description: "Classic restaurant-style stir-fried rice loaded with crunchy carrots, beans, onions, and garlic.",
    ingredients: ["Rice", "Carrot", "Beans", "Onion", "Garlic", "Soy Sauce", "Oil", "Black Pepper", "Salt"],
    requiredIngredients: ["Rice", "Carrot", "Onion", "Garlic"],
    optionalIngredients: ["Beans", "Soy Sauce", "Black Pepper"],
    prepTime: "10 mins",
    cookTime: "12 mins",
    totalMinutes: 22,
    difficulty: "Easy",
    servings: 3,
    isVegetarian: true,
    isVegan: true,
    nutrition: { calories: 340, protein: "7g", carbs: "62g", fat: "8g" },
    instructions: [
      "Heat oil in a wok on high heat and sauté minced garlic.",
      "Add finely chopped carrots, beans, and onions; toss for 3 minutes until crisp-tender.",
      "Add cooked cold rice, soy sauce, salt, and freshly cracked black pepper.",
      "Toss continuously on high heat for 3-4 minutes to develop a smoky wok aroma."
    ]
  },
  {
    id: "rec_23",
    name: "Egg Fried Rice",
    category: "Rice",
    categories: ["Rice", "Egg", "Lunch", "Dinner", "Quick Meals", "High Protein", "Budget Meals"],
    cuisine: "International",
    emoji: "🍚",
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80",
    description: "Fast 15-minute comfort meal: fluffy rice tossed with scrambled eggs, scallions, and pepper.",
    ingredients: ["Rice", "Egg", "Onion", "Garlic", "Soy Sauce", "Oil", "Black Pepper", "Salt"],
    requiredIngredients: ["Rice", "Egg", "Onion"],
    optionalIngredients: ["Garlic", "Soy Sauce", "Black Pepper"],
    prepTime: "5 mins",
    cookTime: "10 mins",
    totalMinutes: 15,
    difficulty: "Easy",
    servings: 2,
    isVegetarian: false,
    isVegan: false,
    nutrition: { calories: 390, protein: "16g", carbs: "54g", fat: "12g" },
    instructions: [
      "Heat oil in a skillet and scramble 2 eggs with a pinch of salt.",
      "Add chopped garlic and onions, cook for 1 minute.",
      "Tip in cooked rice, soy sauce, and generous black pepper.",
      "Stir fry vigorously for 3 minutes until steaming hot."
    ]
  },
  {
    id: "rec_24",
    name: "Schezwan Fried Rice",
    category: "Rice",
    categories: ["Rice", "Vegetarian", "Lunch", "Dinner", "Quick Meals"],
    cuisine: "International",
    emoji: "🌶️",
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80",
    description: "Fiery red Indo-Chinese fried rice tossed with zesty Schezwan sauce, garlic, and fresh veggies.",
    ingredients: ["Rice", "Carrot", "Onion", "Capsicum", "Garlic", "Schezwan Sauce", "Soy Sauce", "Oil"],
    requiredIngredients: ["Rice", "Carrot", "Onion", "Garlic"],
    optionalIngredients: ["Capsicum", "Schezwan Sauce", "Soy Sauce"],
    prepTime: "10 mins",
    cookTime: "12 mins",
    totalMinutes: 22,
    difficulty: "Easy",
    servings: 3,
    isVegetarian: true,
    isVegan: true,
    nutrition: { calories: 360, protein: "6g", carbs: "64g", fat: "9g" },
    instructions: [
      "Sauté chopped garlic, onions, carrots, and capsicum in oil over high heat.",
      "Add 2 tablespoons of Schezwan sauce and 1 teaspoon of soy sauce.",
      "Add cooked rice and toss gently until every grain is coated red.",
      "Cook for 2 more minutes on high flame and serve hot."
    ]
  },
  {
    id: "rec_25",
    name: "Ghee Rice",
    category: "Rice",
    categories: ["Rice", "Kerala", "South Indian", "Vegetarian", "Lunch", "Dinner"],
    cuisine: "Kerala",
    emoji: "🍚",
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80",
    description: "Aromatic Malabar specialty made with Kaima rice, pure ghee, fried onions, cashews, and raisins.",
    ingredients: ["Rice", "Ghee", "Onion", "Cashews", "Raisins", "Cardamom", "Cinnamon", "Cloves", "Salt", "Water"],
    requiredIngredients: ["Rice", "Ghee", "Onion"],
    optionalIngredients: ["Cashews", "Raisins", "Cardamom", "Cinnamon"],
    prepTime: "10 mins",
    cookTime: "20 mins",
    totalMinutes: 30,
    difficulty: "Easy",
    servings: 4,
    isVegetarian: true,
    isVegan: false,
    nutrition: { calories: 380, protein: "6g", carbs: "58g", fat: "14g" },
    instructions: [
      "Fry thinly sliced onions in ghee until golden brown and crispy; set aside for garnish.",
      "Fry cashews and raisins in the same ghee until plump.",
      "Add whole spices (cardamom, cinnamon, cloves) and sauté soaked rice for 2 minutes.",
      "Add boiling water and salt, cover, and cook on low heat until water is absorbed.",
      "Garnish with fried onions, nuts, and raisins before serving."
    ]
  },
  {
    id: "rec_26",
    name: "Jeera Rice",
    category: "Rice",
    categories: ["Rice", "North Indian", "Vegetarian", "Vegan", "Quick Meals", "Budget Meals"],
    cuisine: "North Indian",
    emoji: "🍚",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=600&q=80",
    description: "Fluffy basmati rice tempered with golden roasted cumin seeds and fresh ghee.",
    ingredients: ["Rice", "Cumin Seeds", "Ghee", "Green Chili", "Coriander", "Salt", "Water"],
    requiredIngredients: ["Rice", "Cumin Seeds", "Ghee"],
    optionalIngredients: ["Green Chili", "Coriander", "Salt"],
    prepTime: "5 mins",
    cookTime: "15 mins",
    totalMinutes: 20,
    difficulty: "Easy",
    servings: 3,
    isVegetarian: true,
    isVegan: false,
    nutrition: { calories: 290, protein: "5g", carbs: "52g", fat: "7g" },
    instructions: [
      "Heat ghee or oil in a pan and add whole cumin seeds until they sizzle and release aroma.",
      "Add slit green chili and soaked basmati rice, sauté gently for 1 minute.",
      "Add water and salt, bring to a boil, cover and simmer for 12 minutes.",
      "Fluff gently with a fork and garnish with chopped fresh coriander."
    ]
  },
  {
    id: "rec_27",
    name: "Tomato Rice",
    category: "Rice",
    categories: ["Rice", "South Indian", "Vegetarian", "Vegan", "Budget Meals", "Quick Meals"],
    cuisine: "South Indian",
    emoji: "🍅",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
    description: "Tangy and spiced South Indian thakkali sadam made with juicy ripe tomatoes, onions, and curry leaves.",
    ingredients: ["Rice", "Tomato", "Onion", "Green Chili", "Ginger", "Mustard Seeds", "Curry Leaves", "Turmeric", "Chili Powder", "Oil", "Salt"],
    requiredIngredients: ["Rice", "Tomato", "Onion"],
    optionalIngredients: ["Green Chili", "Curry Leaves", "Ginger", "Mustard Seeds"],
    prepTime: "10 mins",
    cookTime: "18 mins",
    totalMinutes: 28,
    difficulty: "Easy",
    servings: 3,
    isVegetarian: true,
    isVegan: true,
    nutrition: { calories: 310, protein: "6g", carbs: "56g", fat: "7g" },
    instructions: [
      "Heat oil, temper mustard seeds and curry leaves.",
      "Add sliced onions, green chilies, and ginger; sauté till onions turn translucent.",
      "Add chopped tomatoes, turmeric, chili powder, and salt. Cook until tomatoes turn mushy and oil separates.",
      "Mix in cooked rice gently on low heat until thoroughly combined.",
      "Rest for 2 minutes and serve warm with raita or papad."
    ]
  },
  {
    id: "rec_28",
    name: "Lemon Rice",
    category: "Rice",
    categories: ["Rice", "South Indian", "Vegetarian", "Vegan", "Budget Meals", "Quick Meals"],
    cuisine: "South Indian",
    emoji: "🍋",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=600&q=80",
    description: "Vibrant yellow rice infused with freshly squeezed lemon juice, crunchy peanuts, and mustard tempering.",
    ingredients: ["Rice", "Lemon", "Peanuts", "Turmeric", "Mustard Seeds", "Curry Leaves", "Green Chili", "Oil", "Salt"],
    requiredIngredients: ["Rice", "Lemon", "Turmeric"],
    optionalIngredients: ["Peanuts", "Mustard Seeds", "Curry Leaves", "Green Chili"],
    prepTime: "5 mins",
    cookTime: "10 mins",
    totalMinutes: 15,
    difficulty: "Easy",
    servings: 3,
    isVegetarian: true,
    isVegan: true,
    nutrition: { calories: 280, protein: "5g", carbs: "50g", fat: "7g" },
    instructions: [
      "Heat oil in a pan, fry peanuts until crisp, then add mustard seeds, curry leaves, and green chilies.",
      "Turn off the heat and stir in turmeric powder and salt.",
      "Add cooked rice and squeeze fresh lemon juice all over.",
      "Toss gently until rice is uniformly yellow and fragrant."
    ]
  },
  {
    id: "rec_29",
    name: "Coconut Rice",
    category: "Rice",
    categories: ["Rice", "South Indian", "Vegetarian", "Vegan", "Budget Meals"],
    cuisine: "South Indian",
    emoji: "🥥",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=600&q=80",
    description: "Mild, fragrant rice tossed with freshly grated coconut, cashews, and curry leaves in coconut oil.",
    ingredients: ["Rice", "Grated Coconut", "Cashews", "Mustard Seeds", "Curry Leaves", "Green Chili", "Coconut Oil", "Salt"],
    requiredIngredients: ["Rice", "Grated Coconut", "Coconut Oil"],
    optionalIngredients: ["Cashews", "Mustard Seeds", "Curry Leaves"],
    prepTime: "5 mins",
    cookTime: "12 mins",
    totalMinutes: 17,
    difficulty: "Easy",
    servings: 3,
    isVegetarian: true,
    isVegan: true,
    nutrition: { calories: 340, protein: "5g", carbs: "52g", fat: "13g" },
    instructions: [
      "Heat coconut oil in a pan; add mustard seeds, curry leaves, chilies, and cashews.",
      "Add freshly grated coconut and sauté on low flame for 2 minutes without browning.",
      "Add cooked rice and salt; mix thoroughly and serve."
    ]
  },
  {
    id: "rec_30",
    name: "Curd Rice",
    category: "Rice",
    categories: ["Rice", "South Indian", "Vegetarian", "Healthy", "Quick Meals", "Budget Meals"],
    cuisine: "South Indian",
    emoji: "🥣",
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80",
    description: "Cooling and creamy yogurt rice tempered with mustard seeds, curry leaves, and ginger.",
    ingredients: ["Rice", "Curd", "Milk", "Mustard Seeds", "Curry Leaves", "Ginger", "Green Chili", "Oil", "Salt"],
    requiredIngredients: ["Rice", "Curd", "Salt"],
    optionalIngredients: ["Milk", "Mustard Seeds", "Curry Leaves", "Ginger"],
    prepTime: "5 mins",
    cookTime: "5 mins",
    totalMinutes: 10,
    difficulty: "Easy",
    servings: 2,
    isVegetarian: true,
    isVegan: false,
    nutrition: { calories: 230, protein: "7g", carbs: "42g", fat: "4g" },
    instructions: [
      "Mash soft cooked rice lightly while warm.",
      "Mix with fresh curd, a splash of milk, and salt until creamy.",
      "Temper mustard seeds, curry leaves, ginger, and green chili in a teaspoon of oil.",
      "Pour tempering over curd rice, mix gently, and serve chilled."
    ]
  },
  {
    id: "rec_31",
    name: "Vegetable Biryani",
    category: "Rice",
    categories: ["Rice", "Vegetarian", "Lunch", "Dinner", "Indian"],
    cuisine: "Indian",
    emoji: "🍛",
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80",
    description: "Layered royal basmati rice cooked with spiced mixed vegetables, saffron, mint, and fried onions.",
    ingredients: ["Rice", "Carrot", "Potato", "Beans", "Green Peas", "Onion", "Tomato", "Curd", "Biryani Masala", "Mint", "Ghee", "Salt"],
    requiredIngredients: ["Rice", "Potato", "Carrot", "Onion", "Tomato"],
    optionalIngredients: ["Green Peas", "Biryani Masala", "Mint", "Curd"],
    prepTime: "20 mins",
    cookTime: "30 mins",
    totalMinutes: 50,
    difficulty: "Medium",
    servings: 4,
    isVegetarian: true,
    isVegan: false,
    nutrition: { calories: 410, protein: "9g", carbs: "68g", fat: "11g" },
    instructions: [
      "Parboil basmati rice with whole spices until 70% cooked.",
      "Sauté onions, tomatoes, ginger-garlic, curd, and biryani spices with mixed vegetables.",
      "Layer vegetable gravy and parboiled rice in a heavy pot.",
      "Top with mint, coriander, fried onions, and ghee.",
      "Seal pot and cook on low dum heat for 20 minutes."
    ]
  },
  {
    id: "rec_32",
    name: "Chicken Biryani",
    category: "Rice",
    categories: ["Rice", "Chicken", "Lunch", "Dinner", "Indian", "High Protein"],
    cuisine: "Indian",
    emoji: "🍗",
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80",
    description: "World-famous fragrant dum biryani layered with marinated chicken, saffron rice, mint, and caramelized onions.",
    ingredients: ["Rice", "Chicken", "Onion", "Tomato", "Curd", "Ginger", "Garlic", "Biryani Masala", "Mint", "Ghee", "Oil", "Salt"],
    requiredIngredients: ["Rice", "Chicken", "Onion", "Tomato", "Curd"],
    optionalIngredients: ["Ginger", "Garlic", "Biryani Masala", "Mint", "Ghee"],
    prepTime: "30 mins",
    cookTime: "35 mins",
    totalMinutes: 65,
    difficulty: "Hard",
    servings: 4,
    isVegetarian: false,
    isVegan: false,
    nutrition: { calories: 590, protein: "38g", carbs: "64g", fat: "20g" },
    instructions: [
      "Marinate chicken with curd, ginger-garlic paste, biryani masala, chili powder, and salt.",
      "Cook basmati rice with whole spices until 75% cooked and drain.",
      "Cook marinated chicken in a heavy bottom pot with onions and tomatoes until 80% tender.",
      "Layer rice over chicken, top with saffron milk, fried onions, mint, and ghee.",
      "Cover tightly with foil and lid, cook on low dum for 25 minutes."
    ]
  },
  {
    id: "rec_33",
    name: "Egg Biryani",
    category: "Rice",
    categories: ["Rice", "Egg", "Lunch", "Dinner", "Indian", "High Protein", "Budget Meals"],
    cuisine: "Indian",
    emoji: "🥚",
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80",
    description: "Spicy aromatic rice cooked with golden shallow-fried boiled eggs, onions, and biryani spices.",
    ingredients: ["Rice", "Egg", "Onion", "Tomato", "Curd", "Ginger", "Garlic", "Biryani Masala", "Mint", "Oil", "Salt"],
    requiredIngredients: ["Rice", "Egg", "Onion", "Tomato"],
    optionalIngredients: ["Curd", "Biryani Masala", "Mint", "Garlic"],
    prepTime: "15 mins",
    cookTime: "25 mins",
    totalMinutes: 40,
    difficulty: "Medium",
    servings: 3,
    isVegetarian: false,
    isVegan: false,
    nutrition: { calories: 460, protein: "18g", carbs: "60g", fat: "16g" },
    instructions: [
      "Hard boil eggs, prick them, and shallow fry with turmeric and chili powder.",
      "Sauté onions, ginger-garlic paste, and tomatoes with biryani masala and curd.",
      "Add fried eggs into the spicy masala.",
      "Layer with partially cooked basmati rice, cover and cook on low dum for 15 minutes."
    ]
  },
  {
    id: "rec_34",
    name: "Fish Biryani",
    category: "Rice",
    categories: ["Rice", "Fish", "Kerala", "South Indian", "Lunch", "Dinner", "High Protein"],
    cuisine: "Kerala",
    emoji: "🐟",
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80",
    description: "Malabar-style fish biryani prepared with spiced seared fish steaks, ghee rice, and rich masala gravy.",
    ingredients: ["Rice", "Fish", "Onion", "Tomato", "Ginger", "Garlic", "Curd", "Biryani Masala", "Ghee", "Oil", "Salt"],
    requiredIngredients: ["Rice", "Fish", "Onion", "Tomato"],
    optionalIngredients: ["Curd", "Ginger", "Garlic", "Ghee"],
    prepTime: "20 mins",
    cookTime: "30 mins",
    totalMinutes: 50,
    difficulty: "Medium",
    servings: 4,
    isVegetarian: false,
    isVegan: false,
    nutrition: { calories: 510, protein: "34g", carbs: "60g", fat: "15g" },
    instructions: [
      "Marinate fish steaks with chili powder, turmeric, and shallow fry briefly.",
      "Sauté sliced onions, ginger-garlic, tomatoes, curd, and spices to make fish masala.",
      "Place seared fish gently into the masala gravy.",
      "Layer cooked ghee rice over fish, top with fried onions, cashews, and dum steam for 15 minutes."
    ]
  },
  {
    id: "rec_35",
    name: "Mutton Biryani",
    category: "Rice",
    categories: ["Rice", "Meat", "Lunch", "Dinner", "Indian", "High Protein"],
    cuisine: "Indian",
    emoji: "🥩",
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80",
    description: "Rich, aromatic dum biryani with melt-in-the-mouth succulent mutton pieces and spiced long-grain rice.",
    ingredients: ["Rice", "Mutton", "Onion", "Tomato", "Curd", "Ginger", "Garlic", "Biryani Masala", "Ghee", "Mint", "Salt"],
    requiredIngredients: ["Rice", "Mutton", "Onion", "Tomato", "Curd"],
    optionalIngredients: ["Ginger", "Garlic", "Biryani Masala", "Mint", "Ghee"],
    prepTime: "30 mins",
    cookTime: "50 mins",
    totalMinutes: 80,
    difficulty: "Hard",
    servings: 4,
    isVegetarian: false,
    isVegan: false,
    nutrition: { calories: 640, protein: "40g", carbs: "62g", fat: "26g" },
    instructions: [
      "Pressure cook marinated mutton with ginger-garlic, onions, and spices until tender.",
      "Reduce the gravy until thick and rich.",
      "Layer cooked basmati rice over hot mutton gravy.",
      "Top with mint, saffron, and ghee; seal and dum cook on low heat for 20 minutes."
    ]
  },
  {
    id: "rec_36",
    name: "Tomato Pulao",
    category: "Rice",
    categories: ["Rice", "Vegetarian", "Quick Meals", "Budget Meals", "Lunch"],
    cuisine: "North Indian",
    emoji: "🍅",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
    description: "One-pot fragrant spiced rice cooked with fresh ripe tomatoes, onions, and whole garam masala.",
    ingredients: ["Rice", "Tomato", "Onion", "Garlic", "Ginger", "Garam Masala", "Oil", "Salt", "Water"],
    requiredIngredients: ["Rice", "Tomato", "Onion"],
    optionalIngredients: ["Garlic", "Ginger", "Garam Masala"],
    prepTime: "10 mins",
    cookTime: "15 mins",
    totalMinutes: 25,
    difficulty: "Easy",
    servings: 3,
    isVegetarian: true,
    isVegan: true,
    nutrition: { calories: 310, protein: "6g", carbs: "58g", fat: "6g" },
    instructions: [
      "Sauté whole spices, sliced onions, and ginger-garlic paste in oil.",
      "Add pureed tomatoes, garam masala, and salt; cook till fragrant.",
      "Add soaked rice and water, cover and pressure cook for 2 whistles."
    ]
  },
  {
    id: "rec_37",
    name: "Vegetable Pulao",
    category: "Rice",
    categories: ["Rice", "Vegetarian", "Healthy", "Lunch", "Dinner", "Quick Meals"],
    cuisine: "Indian",
    emoji: "🍚",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=600&q=80",
    description: "Mild, fragrant one-pot basmati rice pilaf studded with colorful vegetables and whole spices.",
    ingredients: ["Rice", "Carrot", "Potato", "Beans", "Green Peas", "Onion", "Ghee", "Cumin Seeds", "Salt", "Water"],
    requiredIngredients: ["Rice", "Carrot", "Potato", "Onion"],
    optionalIngredients: ["Green Peas", "Beans", "Ghee", "Cumin Seeds"],
    prepTime: "10 mins",
    cookTime: "18 mins",
    totalMinutes: 28,
    difficulty: "Easy",
    servings: 3,
    isVegetarian: true,
    isVegan: false,
    nutrition: { calories: 330, protein: "7g", carbs: "62g", fat: "7g" },
    instructions: [
      "Heat ghee, sizzle cumin seeds, cardamom, and cinnamon.",
      "Sauté onions and diced vegetables for 3 minutes.",
      "Add soaked basmati rice, water, and salt.",
      "Cover and simmer until rice is tender and water is absorbed."
    ]
  },
  {
    id: "rec_38",
    name: "Chicken Pulao",
    category: "Rice",
    categories: ["Rice", "Chicken", "Lunch", "Dinner", "High Protein", "Quick Meals"],
    cuisine: "Indian",
    emoji: "🍗",
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80",
    description: "Easy one-pot chicken pilaf made by simmering chicken pieces with whole spices and basmati rice.",
    ingredients: ["Rice", "Chicken", "Onion", "Tomato", "Ginger", "Garlic", "Garam Masala", "Oil", "Salt", "Water"],
    requiredIngredients: ["Rice", "Chicken", "Onion", "Tomato"],
    optionalIngredients: ["Ginger", "Garlic", "Garam Masala"],
    prepTime: "15 mins",
    cookTime: "25 mins",
    totalMinutes: 40,
    difficulty: "Easy",
    servings: 3,
    isVegetarian: false,
    isVegan: false,
    nutrition: { calories: 490, protein: "32g", carbs: "56g", fat: "14g" },
    instructions: [
      "Sauté onions, ginger, and garlic in oil until golden.",
      "Add chicken pieces and tomatoes; sear on high heat until chicken changes color.",
      "Add garam masala, soaked rice, water, and salt.",
      "Cover tightly and cook on medium-low heat for 18 minutes until rice is fluffy."
    ]
  },

  // ==================== KERALA SPECIALTIES (39-58) ====================
  {
    id: "rec_39",
    name: "Kerala Parotta",
    category: "Kerala",
    categories: ["Kerala", "South Indian", "Vegetarian", "Bread", "Dinner"],
    cuisine: "Kerala",
    emoji: "🫓",
    image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80",
    description: "Flaky, layered, crispy on the outside and soft on the inside Kerala street food flatbread.",
    ingredients: ["Flour", "Oil", "Sugar", "Water", "Salt"],
    requiredIngredients: ["Flour", "Oil", "Water"],
    optionalIngredients: ["Sugar", "Salt"],
    prepTime: "30 mins",
    cookTime: "15 mins",
    totalMinutes: 45,
    difficulty: "Medium",
    servings: 4,
    isVegetarian: true,
    isVegan: true,
    nutrition: { calories: 310, protein: "6g", carbs: "48g", fat: "11g" },
    instructions: [
      "Knead flour, salt, sugar, water, and oil into a pliable smooth dough.",
      "Rest dough for 30 minutes, divide into balls, roll thinly, and fold into spiral layers.",
      "Flatten gently and cook on a hot tawa with oil until golden brown on both sides.",
      "Clap parottas between hands while hot to release flaky layers."
    ]
  },
  {
    id: "rec_40",
    name: "Chicken Curry",
    category: "Kerala",
    categories: ["Kerala", "Chicken", "South Indian", "Lunch", "Dinner", "High Protein"],
    cuisine: "Kerala",
    emoji: "🍛",
    image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=600&q=80",
    description: "Traditional Kerala style chicken curry cooked in coconut oil with onions, curry leaves, and roasted spices.",
    ingredients: ["Chicken", "Onion", "Tomato", "Ginger", "Garlic", "Coconut Oil", "Curry Leaves", "Chili Powder", "Coriander Powder", "Turmeric", "Garam Masala", "Salt"],
    requiredIngredients: ["Chicken", "Onion", "Tomato", "Coconut Oil"],
    optionalIngredients: ["Curry Leaves", "Ginger", "Garlic", "Garam Masala"],
    prepTime: "15 mins",
    cookTime: "30 mins",
    totalMinutes: 45,
    difficulty: "Easy",
    servings: 4,
    isVegetarian: false,
    isVegan: false,
    nutrition: { calories: 420, protein: "36g", carbs: "12g", fat: "26g" },
    instructions: [
      "Heat coconut oil in a pan, sauté sliced onions, ginger, garlic, and fresh curry leaves until golden.",
      "Add turmeric, coriander, chili, and garam masala powders; roast on low flame for 1 minute.",
      "Add chopped tomatoes and cook until soft.",
      "Add chicken pieces and salt; mix well to coat with masala.",
      "Add 1 cup of water, cover, and simmer for 25 minutes until chicken is tender."
    ]
  },
  {
    id: "rec_41",
    name: "Kerala Beef Curry",
    category: "Kerala",
    categories: ["Kerala", "Meat", "South Indian", "Lunch", "Dinner", "High Protein"],
    cuisine: "Kerala",
    emoji: "🥩",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80",
    description: "Spicy Kerala beef curry slow-cooked with roasted coconut pieces, black pepper, and garlic.",
    ingredients: ["Beef", "Onion", "Tomato", "Ginger", "Garlic", "Coconut Pieces", "Black Pepper", "Chili Powder", "Curry Leaves", "Coconut Oil", "Salt"],
    requiredIngredients: ["Beef", "Onion", "Tomato", "Coconut Oil"],
    optionalIngredients: ["Coconut Pieces", "Black Pepper", "Curry Leaves", "Ginger"],
    prepTime: "20 mins",
    cookTime: "40 mins",
    totalMinutes: 60,
    difficulty: "Medium",
    servings: 4,
    isVegetarian: false,
    isVegan: false,
    nutrition: { calories: 460, protein: "38g", carbs: "10g", fat: "30g" },
    instructions: [
      "Pressure cook beef cubes with turmeric, chili powder, crushed pepper, and salt.",
      "Heat coconut oil, brown small coconut slices (thengakothu) and set aside.",
      "Sauté onions, ginger, garlic, and curry leaves in the same pan.",
      "Add cooked beef with broth, simmer until gravy thickens.",
      "Garnish with browned coconut slices and crushed black pepper."
    ]
  },
  {
    id: "rec_42",
    name: "Fish Curry",
    category: "Kerala",
    categories: ["Kerala", "Fish", "South Indian", "Lunch", "Dinner", "High Protein"],
    cuisine: "Kerala",
    emoji: "🐟",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80",
    description: "Authentic Kerala clay pot meen curry cooked in tangy kudampuli (pot tamarind) and red chili gravy.",
    ingredients: ["Fish", "Shallots", "Tomato", "Ginger", "Garlic", "Kudampuli", "Fenugreek", "Curry Leaves", "Chili Powder", "Turmeric", "Coconut Oil", "Salt"],
    requiredIngredients: ["Fish", "Tomato", "Chili Powder", "Coconut Oil"],
    optionalIngredients: ["Shallots", "Kudampuli", "Fenugreek", "Curry Leaves"],
    prepTime: "15 mins",
    cookTime: "20 mins",
    totalMinutes: 35,
    difficulty: "Easy",
    servings: 3,
    isVegetarian: false,
    isVegan: false,
    nutrition: { calories: 340, protein: "30g", carbs: "8g", fat: "20g" },
    instructions: [
      "Soak kudampuli in warm water.",
      "Heat coconut oil in a clay pot (manchatti), sputter fenugreek seeds and curry leaves.",
      "Sauté shallots, ginger, garlic, and tomatoes.",
      "Add chili powder, turmeric, salt, soaked kudampuli with water, bring to a boil.",
      "Add fish pieces gently, swirl the pot, cover and simmer for 15 minutes."
    ]
  },
  {
    id: "rec_43",
    name: "Meen Pollichathu",
    category: "Kerala",
    categories: ["Kerala", "Fish", "South Indian", "High Protein", "Dinner"],
    cuisine: "Kerala",
    emoji: "🐟",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80",
    description: "Whole pearl spot fish coated in spicy shallot tomato masala, wrapped in banana leaf, and pan-roasted.",
    ingredients: ["Fish", "Banana Leaf", "Shallots", "Tomato", "Ginger", "Garlic", "Curry Leaves", "Chili Powder", "Coconut Oil", "Salt"],
    requiredIngredients: ["Fish", "Tomato", "Shallots", "Coconut Oil"],
    optionalIngredients: ["Banana Leaf", "Ginger", "Garlic", "Curry Leaves"],
    prepTime: "20 mins",
    cookTime: "25 mins",
    totalMinutes: 45,
    difficulty: "Medium",
    servings: 2,
    isVegetarian: false,
    isVegan: false,
    nutrition: { calories: 380, protein: "32g", carbs: "9g", fat: "24g" },
    instructions: [
      "Marinate fish and shallow fry lightly on both sides.",
      "Make thick masala by sautéing shallots, tomatoes, ginger, garlic, and spices in coconut oil.",
      "Coat fish generously with masala on a softened banana leaf.",
      "Wrap leaf into a parcel, tie with twine, and roast on a pan for 6-8 minutes per side."
    ]
  },
  {
    id: "rec_44",
    name: "Vegetable Stew",
    category: "Kerala",
    categories: ["Kerala", "Vegetarian", "Healthy", "Breakfast", "Dinner", "Vegan"],
    cuisine: "Kerala",
    emoji: "🥔",
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80",
    description: "Mild, aromatic Kerala stew with potatoes, carrots, green beans, and peas simmered in rich coconut milk.",
    ingredients: ["Potato", "Carrot", "Beans", "Green Peas", "Onion", "Ginger", "Green Chili", "Coconut Milk", "Cardamom", "Cinnamon", "Coconut Oil", "Salt"],
    requiredIngredients: ["Potato", "Carrot", "Onion", "Coconut Milk"],
    optionalIngredients: ["Beans", "Green Peas", "Ginger", "Cardamom"],
    prepTime: "15 mins",
    cookTime: "20 mins",
    totalMinutes: 35,
    difficulty: "Easy",
    servings: 4,
    isVegetarian: true,
    isVegan: true,
    nutrition: { calories: 280, protein: "5g", carbs: "32g", fat: "16g" },
    instructions: [
      "Heat coconut oil, sauté whole spices, sliced onions, ginger, and slit green chilies.",
      "Add diced potatoes, carrots, and beans with thin coconut milk and salt.",
      "Cook until vegetables are tender.",
      "Stir in thick coconut milk, turn off heat before boiling, and drizzle raw coconut oil on top."
    ]
  },
  {
    id: "rec_45",
    name: "Chicken Stew",
    category: "Kerala",
    categories: ["Kerala", "Chicken", "Breakfast", "Dinner", "High Protein"],
    cuisine: "Kerala",
    emoji: "🍗",
    image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=600&q=80",
    description: "Kerala Christian delicacy of tender chicken and potatoes cooked in delicately spiced coconut milk.",
    ingredients: ["Chicken", "Potato", "Onion", "Ginger", "Garlic", "Green Chili", "Coconut Milk", "Cashews", "Cardamom", "Coconut Oil", "Salt"],
    requiredIngredients: ["Chicken", "Potato", "Onion", "Coconut Milk"],
    optionalIngredients: ["Cashews", "Ginger", "Garlic", "Cardamom"],
    prepTime: "15 mins",
    cookTime: "25 mins",
    totalMinutes: 40,
    difficulty: "Easy",
    servings: 4,
    isVegetarian: false,
    isVegan: false,
    nutrition: { calories: 390, protein: "30g", carbs: "20g", fat: "22g" },
    instructions: [
      "Sauté whole spices, onions, ginger, garlic, and green chilies in coconut oil.",
      "Add chicken and cubed potatoes with thin coconut milk.",
      "Simmer until chicken is cooked through.",
      "Pour thick coconut milk, warm through gently, and garnish with curry leaves."
    ]
  },
  {
    id: "rec_46",
    name: "Kadala Curry",
    category: "Kerala",
    categories: ["Kerala", "South Indian", "Vegetarian", "High Protein", "Vegan", "Budget Meals"],
    cuisine: "Kerala",
    emoji: "🍛",
    image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80",
    description: "Classic black chickpea curry simmered in roasted coconut gravy and tempered with curry leaves.",
    ingredients: ["Black Chickpeas", "Grated Coconut", "Onion", "Tomato", "Ginger", "Garlic", "Curry Leaves", "Coriander Powder", "Chili Powder", "Coconut Oil", "Salt"],
    requiredIngredients: ["Black Chickpeas", "Onion", "Tomato", "Coconut Oil"],
    optionalIngredients: ["Grated Coconut", "Ginger", "Curry Leaves"],
    prepTime: "15 mins",
    cookTime: "30 mins",
    totalMinutes: 45,
    difficulty: "Easy",
    servings: 4,
    isVegetarian: true,
    isVegan: true,
    nutrition: { calories: 320, protein: "12g", carbs: "48g", fat: "10g" },
    instructions: [
      "Pressure cook soaked black chickpeas with salt and water.",
      "Roast grated coconut with shallots and coriander powder until dark brown; grind to a smooth paste.",
      "Sauté onions, tomatoes, and ginger; add cooked chickpeas and ground coconut paste.",
      "Simmer for 10 minutes and temper with mustard seeds and curry leaves."
    ]
  },
  {
    id: "rec_47",
    name: "Avial",
    category: "Kerala",
    categories: ["Kerala", "South Indian", "Vegetarian", "Healthy", "Lunch"],
    cuisine: "Kerala",
    emoji: "🥗",
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80",
    description: "Medley of garden vegetables cooked with coarsely ground coconut, green chilies, cumin, and sour yogurt.",
    ingredients: ["Carrot", "Beans", "Potato", "Raw Banana", "Drumstick", "Grated Coconut", "Curd", "Green Chili", "Cumin Seeds", "Curry Leaves", "Coconut Oil", "Salt"],
    requiredIngredients: ["Carrot", "Potato", "Grated Coconut", "Curd"],
    optionalIngredients: ["Beans", "Raw Banana", "Curry Leaves", "Coconut Oil"],
    prepTime: "20 mins",
    cookTime: "15 mins",
    totalMinutes: 35,
    difficulty: "Easy",
    servings: 4,
    isVegetarian: true,
    isVegan: false,
    nutrition: { calories: 230, protein: "5g", carbs: "28g", fat: "11g" },
    instructions: [
      "Cut vegetables into 2-inch batons and cook with turmeric, salt, and minimal water.",
      "Coarsely crush grated coconut, green chilies, and cumin seeds.",
      "Add coconut mixture and whisked yogurt to cooked vegetables.",
      "Simmer for 2 minutes, turn off heat, and drizzle raw coconut oil with fresh curry leaves."
    ]
  },
  {
    id: "rec_48",
    name: "Thoran",
    category: "Kerala",
    categories: ["Kerala", "South Indian", "Vegetarian", "Vegan", "Healthy", "Quick Meals", "Budget Meals"],
    cuisine: "Kerala",
    emoji: "🥦",
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80",
    description: "Quick Kerala dry vegetable stir fry tossed with fresh coconut, shallots, garlic, and curry leaves.",
    ingredients: ["Cabbage", "Carrot", "Grated Coconut", "Shallots", "Green Chili", "Garlic", "Mustard Seeds", "Curry Leaves", "Coconut Oil", "Salt"],
    requiredIngredients: ["Cabbage", "Carrot", "Grated Coconut", "Coconut Oil"],
    optionalIngredients: ["Shallots", "Green Chili", "Mustard Seeds", "Curry Leaves"],
    prepTime: "10 mins",
    cookTime: "10 mins",
    totalMinutes: 20,
    difficulty: "Easy",
    servings: 3,
    isVegetarian: true,
    isVegan: true,
    nutrition: { calories: 160, protein: "4g", carbs: "18g", fat: "8g" },
    instructions: [
      "Finely shred cabbage and carrots.",
      "Crush coconut with shallots, garlic, green chili, and cumin.",
      "Sputter mustard seeds and curry leaves in coconut oil.",
      "Add shredded vegetables and coconut mixture, cover and steam on low for 6-8 minutes without water."
    ]
  },
  {
    id: "rec_49",
    name: "Theeyal",
    category: "Kerala",
    categories: ["Kerala", "South Indian", "Vegetarian", "Vegan", "Lunch", "Dinner"],
    cuisine: "Kerala",
    emoji: "🍲",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
    description: "Deep roasted spiced coconut curry with shallots and tamarind, creating a rich dark brown sauce.",
    ingredients: ["Shallots", "Grated Coconut", "Tamarind", "Coriander Powder", "Chili Powder", "Fenugreek", "Curry Leaves", "Coconut Oil", "Salt"],
    requiredIngredients: ["Shallots", "Grated Coconut", "Tamarind", "Coconut Oil"],
    optionalIngredients: ["Curry Leaves", "Fenugreek", "Chili Powder"],
    prepTime: "15 mins",
    cookTime: "25 mins",
    totalMinutes: 40,
    difficulty: "Medium",
    servings: 3,
    isVegetarian: true,
    isVegan: true,
    nutrition: { calories: 250, protein: "4g", carbs: "22g", fat: "17g" },
    instructions: [
      "Slow roast grated coconut with curry leaves until dark mahogany brown.",
      "Add spices and grind to a smooth paste without water.",
      "Sauté shallots in coconut oil, add tamarind juice, ground coconut paste, and simmer for 15 minutes."
    ]
  },
  {
    id: "rec_50",
    name: "Egg Roast",
    category: "Kerala",
    categories: ["Kerala", "Egg", "South Indian", "Breakfast", "Dinner", "High Protein", "Quick Meals"],
    cuisine: "Kerala",
    emoji: "🥚",
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=600&q=80",
    description: "Hard-boiled eggs tossed in a thick, spicy caramelized onion, ginger, tomato, and black pepper masala.",
    ingredients: ["Egg", "Onion", "Tomato", "Ginger", "Garlic", "Curry Leaves", "Black Pepper", "Chili Powder", "Coconut Oil", "Salt"],
    requiredIngredients: ["Egg", "Onion", "Tomato", "Coconut Oil"],
    optionalIngredients: ["Ginger", "Garlic", "Curry Leaves", "Black Pepper"],
    prepTime: "10 mins",
    cookTime: "18 mins",
    totalMinutes: 28,
    difficulty: "Easy",
    servings: 2,
    isVegetarian: false,
    isVegan: false,
    nutrition: { calories: 280, protein: "14g", carbs: "12g", fat: "19g" },
    instructions: [
      "Hard boil eggs, peel, and make light vertical slits.",
      "Heat coconut oil, sauté sliced onions slowly until deep golden brown.",
      "Add ginger-garlic paste, curry leaves, chopped tomatoes, pepper, and spices.",
      "Add boiled eggs, toss to coat in thick masala, and cook on low for 5 minutes."
    ]
  },
  {
    id: "rec_51",
    name: "Beef Fry",
    category: "Kerala",
    categories: ["Kerala", "Meat", "South Indian", "Dinner", "High Protein"],
    cuisine: "Kerala",
    emoji: "🥩",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80",
    description: "Famous Kerala beef ularthiyathu: tender beef slow-roasted in coconut oil with crispy coconut chips and crushed pepper.",
    ingredients: ["Beef", "Onion", "Shallots", "Ginger", "Garlic", "Coconut Pieces", "Black Pepper", "Curry Leaves", "Garam Masala", "Coconut Oil", "Salt"],
    requiredIngredients: ["Beef", "Onion", "Coconut Oil", "Black Pepper"],
    optionalIngredients: ["Coconut Pieces", "Shallots", "Curry Leaves", "Ginger"],
    prepTime: "20 mins",
    cookTime: "45 mins",
    totalMinutes: 65,
    difficulty: "Medium",
    servings: 4,
    isVegetarian: false,
    isVegan: false,
    nutrition: { calories: 490, protein: "42g", carbs: "8g", fat: "32g" },
    instructions: [
      "Pressure cook beef cubes with turmeric, chili, coriander, crushed pepper, and ginger-garlic.",
      "In an iron pan, heat coconut oil and fry coconut chips until golden.",
      "Add shallots and curry leaves; then add cooked beef.",
      "Roast on medium flame stirring continuously until dark brown and aromatic."
    ]
  },
  {
    id: "rec_52",
    name: "Chicken Fry",
    category: "Kerala",
    categories: ["Kerala", "Chicken", "Snacks", "South Indian", "High Protein", "Quick Meals"],
    cuisine: "Kerala",
    emoji: "🍗",
    image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80",
    description: "Crispy Kerala style chicken fry marinated with crushed shallots, ginger, chili, and curry leaves.",
    ingredients: ["Chicken", "Shallots", "Ginger", "Garlic", "Chili Powder", "Turmeric", "Black Pepper", "Curry Leaves", "Coconut Oil", "Salt"],
    requiredIngredients: ["Chicken", "Chili Powder", "Coconut Oil", "Salt"],
    optionalIngredients: ["Shallots", "Ginger", "Curry Leaves", "Black Pepper"],
    prepTime: "15 mins",
    cookTime: "15 mins",
    totalMinutes: 30,
    difficulty: "Easy",
    servings: 3,
    isVegetarian: false,
    isVegan: false,
    nutrition: { calories: 380, protein: "34g", carbs: "6g", fat: "24g" },
    instructions: [
      "Marinate chicken with crushed shallots, ginger, garlic, chili powder, turmeric, and salt for 20 mins.",
      "Heat coconut oil in a pan, add fresh curry leaves.",
      "Shallow fry chicken pieces on medium heat until crisp, golden, and cooked through."
    ]
  },
  {
    id: "rec_53",
    name: "Fish Fry",
    category: "Kerala",
    categories: ["Kerala", "Fish", "South Indian", "High Protein", "Quick Meals"],
    cuisine: "Kerala",
    emoji: "🐟",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80",
    description: "Crispy pan-seared fish slices coated in red chili, pepper, turmeric, and lemon marinade.",
    ingredients: ["Fish", "Chili Powder", "Turmeric", "Black Pepper", "Lemon Juice", "Coconut Oil", "Curry Leaves", "Salt"],
    requiredIngredients: ["Fish", "Chili Powder", "Turmeric", "Coconut Oil"],
    optionalIngredients: ["Lemon Juice", "Black Pepper", "Curry Leaves"],
    prepTime: "10 mins",
    cookTime: "10 mins",
    totalMinutes: 20,
    difficulty: "Easy",
    servings: 2,
    isVegetarian: false,
    isVegan: false,
    nutrition: { calories: 290, protein: "28g", carbs: "3g", fat: "18g" },
    instructions: [
      "Make a paste of chili powder, turmeric, pepper, lemon juice, salt, and water.",
      "Apply evenly on fish slices and rest for 10 minutes.",
      "Shallow fry in coconut oil with curry leaves until crispy on both sides."
    ]
  },
  {
    id: "rec_54",
    name: "Kerala Sambar",
    category: "Kerala",
    categories: ["Kerala", "South Indian", "Vegetarian", "Healthy", "Lunch"],
    cuisine: "Kerala",
    emoji: "🍲",
    image: "https://images.unsplash.com/photo-1610057099431-d73a1c9d2f2f?auto=format&fit=crop&w=600&q=80",
    description: "Hearty mixed vegetable and lentil stew flavored with roasted spices and roasted coconut.",
    ingredients: ["Toor Dal", "Drumstick", "Carrot", "Potato", "Tomato", "Shallots", "Grated Coconut", "Sambar Powder", "Curry Leaves", "Coconut Oil", "Salt"],
    requiredIngredients: ["Toor Dal", "Potato", "Tomato", "Carrot"],
    optionalIngredients: ["Drumstick", "Grated Coconut", "Curry Leaves", "Shallots"],
    prepTime: "15 mins",
    cookTime: "25 mins",
    totalMinutes: 40,
    difficulty: "Easy",
    servings: 4,
    isVegetarian: true,
    isVegan: true,
    nutrition: { calories: 240, protein: "9g", carbs: "38g", fat: "6g" },
    instructions: [
      "Cook dal and chopped vegetables until soft.",
      "Roast coconut and sambar powder and grind to a paste.",
      "Combine dal, vegetables, tamarind water, and coconut paste; boil for 5 minutes.",
      "Temper with mustard seeds, shallots, and curry leaves."
    ]
  },
  {
    id: "rec_55",
    name: "Rasam",
    category: "Kerala",
    categories: ["Kerala", "South Indian", "Vegetarian", "Vegan", "Healthy", "Quick Meals", "Budget Meals"],
    cuisine: "South Indian",
    emoji: "🥣",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
    description: "Zesty, peppery, soothing tomato and tamarind broth tempered with cumin, garlic, and mustard seeds.",
    ingredients: ["Tomato", "Tamarind", "Garlic", "Black Pepper", "Cumin Seeds", "Mustard Seeds", "Curry Leaves", "Coriander", "Oil", "Salt"],
    requiredIngredients: ["Tomato", "Garlic", "Black Pepper"],
    optionalIngredients: ["Tamarind", "Cumin Seeds", "Curry Leaves", "Coriander"],
    prepTime: "5 mins",
    cookTime: "10 mins",
    totalMinutes: 15,
    difficulty: "Easy",
    servings: 4,
    isVegetarian: true,
    isVegan: true,
    nutrition: { calories: 70, protein: "2g", carbs: "12g", fat: "2g" },
    instructions: [
      "Crush tomatoes, garlic, cumin, and black pepper.",
      "Boil with tamarind water, turmeric, and salt until frothy.",
      "Turn off before it rolls into a heavy boil.",
      "Temper with mustard seeds and fresh coriander leaves."
    ]
  },
  {
    id: "rec_56",
    name: "Pappadam & Curry",
    category: "Kerala",
    categories: ["Kerala", "Vegetarian", "Quick Meals", "Budget Meals", "Lunch"],
    cuisine: "Kerala",
    emoji: "🫓",
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80",
    description: "Crispy fried lentil pappadams served alongside hot comforting dhal and rice.",
    ingredients: ["Pappadam", "Toor Dal", "Turmeric", "Oil", "Salt"],
    requiredIngredients: ["Pappadam", "Toor Dal", "Oil"],
    optionalIngredients: ["Turmeric", "Salt"],
    prepTime: "5 mins",
    cookTime: "10 mins",
    totalMinutes: 15,
    difficulty: "Easy",
    servings: 2,
    isVegetarian: true,
    isVegan: true,
    nutrition: { calories: 210, protein: "7g", carbs: "26g", fat: "9g" },
    instructions: [
      "Deep fry pappadams in hot oil until they puff up crisp and golden.",
      "Serve hot with steamed rice and warm dhal."
    ]
  },
  {
    id: "rec_57",
    name: "Kappa & Fish Curry",
    category: "Kerala",
    categories: ["Kerala", "Fish", "South Indian", "Lunch", "Dinner", "High Protein"],
    cuisine: "Kerala",
    emoji: "🥔",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80",
    description: "Signature Kerala combination: Boiled mashed tapioca tempered with coconut served with fiery spicy fish curry.",
    ingredients: ["Tapioca", "Grated Coconut", "Fish", "Shallots", "Chili Powder", "Curry Leaves", "Coconut Oil", "Salt"],
    requiredIngredients: ["Tapioca", "Fish", "Chili Powder", "Coconut Oil"],
    optionalIngredients: ["Grated Coconut", "Shallots", "Curry Leaves"],
    prepTime: "20 mins",
    cookTime: "30 mins",
    totalMinutes: 50,
    difficulty: "Medium",
    servings: 4,
    isVegetarian: false,
    isVegan: false,
    nutrition: { calories: 480, protein: "28g", carbs: "68g", fat: "12g" },
    instructions: [
      "Boil tapioca cubes with salt and turmeric until tender; drain water.",
      "Coarsely grind coconut with green chilies, garlic, and cumin; mix with mashed tapioca.",
      "Pair with spicy hot Kerala fish curry."
    ]
  },
  {
    id: "rec_58",
    name: "Kerala Beef Roast",
    category: "Kerala",
    categories: ["Kerala", "Meat", "South Indian", "Dinner", "High Protein"],
    cuisine: "Kerala",
    emoji: "🥩",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80",
    description: "Tender beef chunks slow-roasted with caramelized onions, tomatoes, and freshly ground garam masala.",
    ingredients: ["Beef", "Onion", "Tomato", "Ginger", "Garlic", "Curry Leaves", "Garam Masala", "Coconut Oil", "Salt"],
    requiredIngredients: ["Beef", "Onion", "Tomato", "Coconut Oil"],
    optionalIngredients: ["Ginger", "Garlic", "Curry Leaves", "Garam Masala"],
    prepTime: "15 mins",
    cookTime: "40 mins",
    totalMinutes: 55,
    difficulty: "Medium",
    servings: 4,
    isVegetarian: false,
    isVegan: false,
    nutrition: { calories: 440, protein: "38g", carbs: "8g", fat: "28g" },
    instructions: [
      "Pressure cook beef with spice powders until tender.",
      "Sauté onions and tomatoes in coconut oil until thick paste forms.",
      "Add beef, roast on medium heat until coated and dry."
    ]
  },

  // ==================== CHICKEN & MEAT (59-80) ====================
  {
    id: "rec_71",
    name: "Chicken 65",
    category: "Chicken",
    categories: ["Chicken", "Snacks", "South Indian", "High Protein", "Quick Meals"],
    cuisine: "South Indian",
    emoji: "🍗",
    image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80",
    description: "Spicy, crispy, deep-fried chicken bites tossed with tempered curry leaves, green chilies, and garlic.",
    ingredients: ["Chicken", "Curd", "Ginger", "Garlic", "Chili Powder", "Corn Flour", "Curry Leaves", "Oil", "Salt"],
    requiredIngredients: ["Chicken", "Curd", "Chili Powder", "Oil"],
    optionalIngredients: ["Corn Flour", "Ginger", "Garlic", "Curry Leaves"],
    prepTime: "15 mins",
    cookTime: "12 mins",
    totalMinutes: 27,
    difficulty: "Easy",
    servings: 3,
    isVegetarian: false,
    isVegan: false,
    nutrition: { calories: 360, protein: "30g", carbs: "8g", fat: "22g" },
    instructions: [
      "Marinate boneless chicken cubes with curd, chili powder, ginger-garlic, corn flour, and salt.",
      "Deep fry chicken until crunchy and cooked through.",
      "In another pan, sauté garlic, green chilies, and curry leaves; toss fried chicken into the seasoning."
    ]
  },
  {
    id: "rec_74",
    name: "Chicken Tikka",
    category: "Chicken",
    categories: ["Chicken", "North Indian", "High Protein", "Healthy", "Dinner"],
    cuisine: "North Indian",
    emoji: "🍗",
    image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=600&q=80",
    description: "Succulent boneless chicken marinated in yogurt, aromatic tandoori spices, and grilled to smoky perfection.",
    ingredients: ["Chicken", "Curd", "Lemon Juice", "Ginger", "Garlic", "Chili Powder", "Garam Masala", "Butter", "Salt"],
    requiredIngredients: ["Chicken", "Curd", "Chili Powder", "Lemon Juice"],
    optionalIngredients: ["Ginger", "Garlic", "Garam Masala", "Butter"],
    prepTime: "20 mins",
    cookTime: "15 mins",
    totalMinutes: 35,
    difficulty: "Easy",
    servings: 3,
    isVegetarian: false,
    isVegan: false,
    nutrition: { calories: 310, protein: "38g", carbs: "4g", fat: "14g" },
    instructions: [
      "Marinate chicken cubes with yogurt, lemon juice, chili powder, garam masala, and ginger-garlic paste for at least 30 minutes.",
      "Thread onto skewers and grill in an oven or pan on high heat, basting with melted butter until charred and juicy."
    ]
  },
  {
    id: "rec_76",
    name: "Butter Chicken",
    category: "Chicken",
    categories: ["Chicken", "North Indian", "Dinner", "Lunch", "High Protein"],
    cuisine: "North Indian",
    emoji: "🍗",
    image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=600&q=80",
    description: "Tender grilled chicken pieces simmered in a silky, creamy, buttery tomato sauce scented with kasuri methi.",
    ingredients: ["Chicken", "Tomato", "Butter", "Cream", "Onion", "Cashews", "Ginger", "Garlic", "Kasuri Methi", "Chili Powder", "Garam Masala", "Sugar", "Salt"],
    requiredIngredients: ["Chicken", "Tomato", "Butter", "Cream", "Onion"],
    optionalIngredients: ["Cashews", "Kasuri Methi", "Garam Masala", "Ginger"],
    prepTime: "20 mins",
    cookTime: "25 mins",
    totalMinutes: 45,
    difficulty: "Medium",
    servings: 4,
    isVegetarian: false,
    isVegan: false,
    nutrition: { calories: 520, protein: "34g", carbs: "14g", fat: "36g" },
    instructions: [
      "Grill or pan-sear marinated chicken pieces.",
      "Simmer tomatoes, onions, cashews, ginger, and garlic; blend into a silky smooth gravy.",
      "Heat butter, add chili powder, pureed sauce, cream, sugar, and cooked chicken.",
      "Simmer for 8 minutes, finish with crushed kasuri methi and extra butter."
    ]
  },
  {
    id: "rec_80",
    name: "Chicken Noodles",
    category: "Chicken",
    categories: ["Chicken", "Quick Meals", "Pasta", "Dinner", "High Protein"],
    cuisine: "International",
    emoji: "🍜",
    image: "https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=600&q=80",
    description: "Wok-tossed noodles with shredded chicken, crunchy carrots, cabbage, garlic, and soy sauce.",
    ingredients: ["Noodles", "Chicken", "Carrot", "Cabbage", "Onion", "Garlic", "Soy Sauce", "Oil", "Black Pepper", "Salt"],
    requiredIngredients: ["Noodles", "Chicken", "Carrot", "Onion"],
    optionalIngredients: ["Cabbage", "Garlic", "Soy Sauce", "Black Pepper"],
    prepTime: "10 mins",
    cookTime: "12 mins",
    totalMinutes: 22,
    difficulty: "Easy",
    servings: 3,
    isVegetarian: false,
    isVegan: false,
    nutrition: { calories: 420, protein: "28g", carbs: "52g", fat: "12g" },
    instructions: [
      "Boil noodles al dente, drain, rinse with cold water, and toss with a drop of oil.",
      "Stir fry chicken strips with minced garlic in a wok on high heat until cooked.",
      "Add shredded carrots and cabbage; toss for 2 minutes.",
      "Add noodles, soy sauce, black pepper, and salt; toss vigorously on high flame."
    ]
  },
  {
    id: "rec_81",
    name: "Chicken Pasta",
    category: "Chicken",
    categories: ["Chicken", "Pasta", "Dinner", "International", "High Protein"],
    cuisine: "International",
    emoji: "🍝",
    image: "https://images.unsplash.com/photo-1621996346565-e3d5d6281699?auto=format&fit=crop&w=600&q=80",
    description: "Penne pasta tossed with tender sautéed chicken breast, ripe tomato sauce, garlic, and herbs.",
    ingredients: ["Pasta", "Chicken", "Tomato", "Garlic", "Onion", "Olive Oil", "Black Pepper", "Oregano", "Salt"],
    requiredIngredients: ["Pasta", "Chicken", "Tomato", "Garlic"],
    optionalIngredients: ["Onion", "Olive Oil", "Oregano", "Black Pepper"],
    prepTime: "10 mins",
    cookTime: "15 mins",
    totalMinutes: 25,
    difficulty: "Easy",
    servings: 3,
    isVegetarian: false,
    isVegan: false,
    nutrition: { calories: 460, protein: "32g", carbs: "58g", fat: "11g" },
    instructions: [
      "Boil penne pasta in salted water until al dente.",
      "Sauté chicken strips in olive oil with garlic until golden.",
      "Add crushed tomatoes, oregano, black pepper, and simmer until sauce thickens.",
      "Toss in cooked pasta, coat with sauce, and serve."
    ]
  },
  {
    id: "rec_82",
    name: "Chicken Wrap",
    category: "Chicken",
    categories: ["Chicken", "Quick Meals", "Snacks", "High Protein", "Fast Food"],
    cuisine: "International",
    emoji: "🌯",
    image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80",
    description: "Warm tortilla or flatbread rolled with spiced chicken strips, crunchy lettuce, onions, and garlic sauce.",
    ingredients: ["Bread", "Chicken", "Onion", "Tomato", "Mayonnaise", "Garlic", "Chili Powder", "Oil", "Salt"],
    requiredIngredients: ["Bread", "Chicken", "Onion", "Tomato"],
    optionalIngredients: ["Mayonnaise", "Garlic", "Chili Powder"],
    prepTime: "10 mins",
    cookTime: "10 mins",
    totalMinutes: 20,
    difficulty: "Easy",
    servings: 2,
    isVegetarian: false,
    isVegan: false,
    nutrition: { calories: 390, protein: "26g", carbs: "36g", fat: "14g" },
    instructions: [
      "Sear spiced chicken strips on a skillet until juicy and browned.",
      "Warm flatbread or tortilla.",
      "Spread garlic mayo, add sliced onions, tomatoes, and cooked chicken.",
      "Roll tightly into a wrap and serve."
    ]
  },
  {
    id: "rec_84",
    name: "Chicken Soup",
    category: "Chicken",
    categories: ["Chicken", "Healthy", "Dinner", "High Protein", "Quick Meals"],
    cuisine: "International",
    emoji: "🍲",
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80",
    description: "Soothing clear chicken broth simmered with tender shredded chicken, carrots, ginger, and black pepper.",
    ingredients: ["Chicken", "Carrot", "Onion", "Ginger", "Garlic", "Black Pepper", "Butter", "Salt", "Water"],
    requiredIngredients: ["Chicken", "Carrot", "Onion"],
    optionalIngredients: ["Ginger", "Garlic", "Black Pepper", "Butter"],
    prepTime: "10 mins",
    cookTime: "20 mins",
    totalMinutes: 30,
    difficulty: "Easy",
    servings: 3,
    isVegetarian: false,
    isVegan: false,
    nutrition: { calories: 210, protein: "24g", carbs: "8g", fat: "8g" },
    instructions: [
      "Simmer chicken pieces with ginger, garlic, onions, and salt in water for 15 minutes.",
      "Remove chicken, shred meat, and return to simmering broth.",
      "Add diced carrots, simmer 5 minutes, finish with black pepper and fresh herbs."
    ]
  },

  // ==================== VEGETARIAN CLASSICS (105-120) ====================
  {
    id: "rec_111",
    name: "Paneer Butter Masala",
    category: "Vegetarian",
    categories: ["Vegetarian", "North Indian", "Dinner", "Lunch", "High Protein"],
    cuisine: "North Indian",
    emoji: "🍛",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
    description: "Soft fresh paneer cubes simmered in a luscious, mildly sweet, buttery tomato cashew sauce.",
    ingredients: ["Paneer", "Tomato", "Butter", "Cream", "Onion", "Cashews", "Ginger", "Garlic", "Garam Masala", "Kasuri Methi", "Salt"],
    requiredIngredients: ["Paneer", "Tomato", "Butter", "Onion"],
    optionalIngredients: ["Cream", "Cashews", "Kasuri Methi", "Garlic"],
    prepTime: "15 mins",
    cookTime: "20 mins",
    totalMinutes: 35,
    difficulty: "Easy",
    servings: 4,
    isVegetarian: true,
    isVegan: false,
    nutrition: { calories: 460, protein: "18g", carbs: "16g", fat: "36g" },
    instructions: [
      "Cook tomatoes, onions, ginger, garlic, and cashews; puree into a fine silk gravy.",
      "Melt butter in a pan, add chili powder, and pour the pureed gravy.",
      "Simmer for 8 minutes, add soft paneer cubes and cream.",
      "Finish with crushed kasuri methi and extra butter."
    ]
  },
  {
    id: "rec_113",
    name: "Palak Paneer",
    category: "Vegetarian",
    categories: ["Vegetarian", "Healthy", "North Indian", "High Protein", "Dinner"],
    cuisine: "North Indian",
    emoji: "🥬",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
    description: "Wholesome smooth spinach gravy infused with garlic, cumin, and soft paneer cubes.",
    ingredients: ["Spinach", "Paneer", "Onion", "Tomato", "Garlic", "Ginger", "Green Chili", "Cream", "Butter", "Salt"],
    requiredIngredients: ["Spinach", "Paneer", "Garlic", "Onion"],
    optionalIngredients: ["Tomato", "Cream", "Butter", "Ginger"],
    prepTime: "15 mins",
    cookTime: "15 mins",
    totalMinutes: 30,
    difficulty: "Easy",
    servings: 3,
    isVegetarian: true,
    isVegan: false,
    nutrition: { calories: 340, protein: "16g", carbs: "10g", fat: "26g" },
    instructions: [
      "Blanch spinach leaves in boiling water for 2 minutes, plunge into ice water, and puree.",
      "Sauté onions, ginger, garlic, and tomatoes in butter.",
      "Add spinach puree, salt, and garam masala; simmer for 4 minutes.",
      "Stir in paneer cubes and a swirl of fresh cream."
    ]
  },
  {
    id: "rec_114",
    name: "Chana Masala",
    category: "Vegetarian",
    categories: ["Vegetarian", "Vegan", "North Indian", "High Protein", "Budget Meals", "Lunch"],
    cuisine: "North Indian",
    emoji: "🍲",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
    description: "Tender chickpeas simmered in a robust, tangy, and deeply spiced onion tomato gravy.",
    ingredients: ["Chickpeas", "Onion", "Tomato", "Ginger", "Garlic", "Chana Masala", "Cumin Seeds", "Coriander", "Oil", "Salt"],
    requiredIngredients: ["Chickpeas", "Onion", "Tomato"],
    optionalIngredients: ["Ginger", "Garlic", "Chana Masala", "Coriander"],
    prepTime: "15 mins",
    cookTime: "25 mins",
    totalMinutes: 40,
    difficulty: "Easy",
    servings: 4,
    isVegetarian: true,
    isVegan: true,
    nutrition: { calories: 330, protein: "14g", carbs: "52g", fat: "8g" },
    instructions: [
      "Pressure cook soaked chickpeas until tender.",
      "Sauté cumin, finely chopped onions, ginger, and garlic in oil until browned.",
      "Add chopped tomatoes, chana masala spices, and cook till oil separates.",
      "Add cooked chickpeas with broth, mash a few spoonfuls to thicken the gravy, and simmer 10 minutes."
    ]
  },
  {
    id: "rec_116",
    name: "Dal Fry",
    category: "Vegetarian",
    categories: ["Vegetarian", "Vegan", "Healthy", "Budget Meals", "Quick Meals", "Lunch", "Dinner"],
    cuisine: "Indian",
    emoji: "🍲",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
    description: "Golden yellow lentils cooked and tempered with cumin seeds, garlic, onions, tomatoes, and ghee.",
    ingredients: ["Toor Dal", "Onion", "Tomato", "Garlic", "Ginger", "Cumin Seeds", "Ghee", "Turmeric", "Coriander", "Salt"],
    requiredIngredients: ["Toor Dal", "Onion", "Tomato", "Garlic"],
    optionalIngredients: ["Ginger", "Cumin Seeds", "Ghee", "Coriander"],
    prepTime: "10 mins",
    cookTime: "20 mins",
    totalMinutes: 30,
    difficulty: "Easy",
    servings: 4,
    isVegetarian: true,
    isVegan: false,
    nutrition: { calories: 220, protein: "11g", carbs: "34g", fat: "5g" },
    instructions: [
      "Cook toor dal with turmeric, salt, and water until soft and creamy.",
      "Heat ghee, sauté cumin seeds, minced garlic, onions, and tomatoes until soft.",
      "Pour tempering into cooked dal, simmer for 3 minutes, and finish with fresh coriander."
    ]
  },

  // ==================== PASTA & QUICK MEALS (121-135) ====================
  {
    id: "rec_125",
    name: "Pasta Arrabbiata",
    category: "Pasta",
    categories: ["Pasta", "Vegetarian", "Vegan", "Quick Meals", "Budget Meals", "Dinner"],
    cuisine: "Italian",
    emoji: "🍝",
    image: "https://images.unsplash.com/photo-1621996346565-e3d5d6281699?auto=format&fit=crop&w=600&q=80",
    description: "Classic spicy Roman pasta tossed in garlic, olive oil, sweet tomatoes, and fiery red chili flakes.",
    ingredients: ["Pasta", "Tomato", "Garlic", "Chili Flakes", "Olive Oil", "Oregano", "Basil", "Salt"],
    requiredIngredients: ["Pasta", "Tomato", "Garlic", "Olive Oil"],
    optionalIngredients: ["Chili Flakes", "Oregano", "Basil"],
    prepTime: "5 mins",
    cookTime: "15 mins",
    totalMinutes: 20,
    difficulty: "Easy",
    servings: 2,
    isVegetarian: true,
    isVegan: true,
    nutrition: { calories: 340, protein: "9g", carbs: "58g", fat: "8g" },
    instructions: [
      "Boil pasta in salted water until al dente.",
      "Gently heat olive oil with sliced garlic and red chili flakes.",
      "Add crushed tomatoes and salt, simmer for 10 minutes until sauce thickens.",
      "Toss pasta directly into the sauce with pasta cooking water and fresh basil."
    ]
  },
  {
    id: "rec_126",
    name: "Creamy Garlic Pasta",
    category: "Pasta",
    categories: ["Pasta", "Vegetarian", "Quick Meals", "Dinner"],
    cuisine: "Italian",
    emoji: "🍝",
    image: "https://images.unsplash.com/photo-1621996346565-e3d5d6281699?auto=format&fit=crop&w=600&q=80",
    description: "Silky, rich pasta tossed in a luxurious garlic butter and cream sauce with cracked black pepper.",
    ingredients: ["Pasta", "Milk", "Butter", "Garlic", "Cheese", "Black Pepper", "Salt"],
    requiredIngredients: ["Pasta", "Milk", "Butter", "Garlic"],
    optionalIngredients: ["Cheese", "Black Pepper"],
    prepTime: "5 mins",
    cookTime: "12 mins",
    totalMinutes: 17,
    difficulty: "Easy",
    servings: 2,
    isVegetarian: true,
    isVegan: false,
    nutrition: { calories: 410, protein: "12g", carbs: "52g", fat: "18g" },
    instructions: [
      "Boil pasta until al dente.",
      "Melt butter, sauté minced garlic for 1 minute.",
      "Add milk/cream, simmer gently, then stir in cheese and black pepper until silky.",
      "Toss cooked pasta in sauce and serve immediately."
    ]
  },
  {
    id: "rec_127",
    name: "Tomato Pasta",
    category: "Pasta",
    categories: ["Pasta", "Vegetarian", "Vegan", "Quick Meals", "Budget Meals"],
    cuisine: "Italian",
    emoji: "🍝",
    image: "https://images.unsplash.com/photo-1621996346565-e3d5d6281699?auto=format&fit=crop&w=600&q=80",
    description: "Fresh and light homemade tomato basil sauce tossed with tender spaghetti.",
    ingredients: ["Pasta", "Tomato", "Onion", "Garlic", "Olive Oil", "Black Pepper", "Salt"],
    requiredIngredients: ["Pasta", "Tomato", "Garlic", "Olive Oil"],
    optionalIngredients: ["Onion", "Black Pepper"],
    prepTime: "5 mins",
    cookTime: "15 mins",
    totalMinutes: 20,
    difficulty: "Easy",
    servings: 2,
    isVegetarian: true,
    isVegan: true,
    nutrition: { calories: 320, protein: "8g", carbs: "56g", fat: "7g" },
    instructions: [
      "Cook pasta in boiling salted water.",
      "Sauté chopped onions and garlic in olive oil, add chopped ripe tomatoes.",
      "Simmer sauce until glossy, season with pepper and salt.",
      "Toss pasta in sauce and enjoy hot."
    ]
  },

  // ==================== DESSERTS & DRINKS (151-185) ====================
  {
    id: "rec_151",
    name: "Payasam",
    category: "Desserts",
    categories: ["Desserts", "Kerala", "South Indian", "Vegetarian"],
    cuisine: "Kerala",
    emoji: "🥣",
    image: "https://images.unsplash.com/photo-1584776296944-ab6fb57b0bdd?auto=format&fit=crop&w=600&q=80",
    description: "Rich, festive South Indian dessert pudding cooked with roasted vermicelli, milk, sugar, cardamom, and ghee-roasted nuts.",
    ingredients: ["Semiya", "Milk", "Sugar", "Ghee", "Cashews", "Raisins", "Cardamom"],
    requiredIngredients: ["Milk", "Sugar", "Ghee"],
    optionalIngredients: ["Semiya", "Cashews", "Raisins", "Cardamom"],
    prepTime: "5 mins",
    cookTime: "15 mins",
    totalMinutes: 20,
    difficulty: "Easy",
    servings: 4,
    isVegetarian: true,
    isVegan: false,
    nutrition: { calories: 290, protein: "6g", carbs: "44g", fat: "10g" },
    instructions: [
      "Roast cashews, raisins, and vermicelli in ghee until golden.",
      "Bring milk to a boil and simmer roasted vermicelli until soft.",
      "Add sugar and crushed cardamom powder; simmer for 3 minutes.",
      "Garnish with golden cashews and raisins; serve warm or chilled."
    ]
  },
  {
    id: "rec_176",
    name: "Fresh Lime Juice",
    category: "Drinks",
    categories: ["Drinks", "Healthy", "Quick Meals", "Budget Meals", "Vegan"],
    cuisine: "International",
    emoji: "🍋",
    image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80",
    description: "Refreshing sweet and salty fresh lime cooler served over ice cubes with a hint of mint.",
    ingredients: ["Lemon", "Sugar", "Salt", "Water", "Mint", "Ice"],
    requiredIngredients: ["Lemon", "Sugar", "Water"],
    optionalIngredients: ["Salt", "Mint", "Ice"],
    prepTime: "3 mins",
    cookTime: "0 mins",
    totalMinutes: 3,
    difficulty: "Easy",
    servings: 2,
    isVegetarian: true,
    isVegan: true,
    nutrition: { calories: 60, protein: "0g", carbs: "16g", fat: "0g" },
    instructions: [
      "Squeeze fresh lemon juice into chilled water.",
      "Add sugar and a tiny pinch of salt; stir vigorously until dissolved.",
      "Pour over ice cubes and garnish with fresh mint leaves."
    ]
  },
  {
    id: "rec_177",
    name: "Mango Shake",
    category: "Drinks",
    categories: ["Drinks", "Desserts", "Healthy", "Vegetarian", "Quick Meals"],
    cuisine: "International",
    emoji: "🥭",
    image: "https://images.unsplash.com/photo-1546173159-315724a31696?auto=format&fit=crop&w=600&q=80",
    description: "Thick, creamy tropical shake blended with sweet ripe mango pulp, chilled milk, and a touch of honey.",
    ingredients: ["Mango", "Milk", "Sugar", "Ice", "Cardamom"],
    requiredIngredients: ["Mango", "Milk"],
    optionalIngredients: ["Sugar", "Ice", "Cardamom"],
    prepTime: "5 mins",
    cookTime: "0 mins",
    totalMinutes: 5,
    difficulty: "Easy",
    servings: 2,
    isVegetarian: true,
    isVegan: false,
    nutrition: { calories: 210, protein: "6g", carbs: "38g", fat: "4g" },
    instructions: [
      "Peel and chop fresh sweet ripe mangoes.",
      "Add mango chunks, chilled milk, sugar, and ice to a blender.",
      "Blend until velvety smooth and pour into tall glasses."
    ]
  },
  {
    id: "rec_178",
    name: "Banana Shake",
    category: "Drinks",
    categories: ["Drinks", "Healthy", "Breakfast", "High Protein", "Quick Meals", "Budget Meals"],
    cuisine: "International",
    emoji: "🍌",
    image: "https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=600&q=80",
    description: "Creamy, naturally sweet energy shake made with ripe bananas, cold milk, and honey.",
    ingredients: ["Banana", "Milk", "Honey", "Ice", "Cinnamon"],
    requiredIngredients: ["Banana", "Milk"],
    optionalIngredients: ["Honey", "Ice", "Cinnamon"],
    prepTime: "3 mins",
    cookTime: "0 mins",
    totalMinutes: 3,
    difficulty: "Easy",
    servings: 2,
    isVegetarian: true,
    isVegan: false,
    nutrition: { calories: 190, protein: "6g", carbs: "36g", fat: "3g" },
    instructions: [
      "Slice ripe bananas and place in a blender with cold milk and honey.",
      "Blend until frothy and smooth, sprinkle with cinnamon, and serve."
    ]
  },
  {
    id: "rec_181",
    name: "Sweet Lassi",
    category: "Drinks",
    categories: ["Drinks", "North Indian", "Vegetarian", "Healthy", "Quick Meals"],
    cuisine: "North Indian",
    emoji: "🥛",
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80",
    description: "Traditional Punjabi thick yogurt drink blended with sugar, rose water, and a pinch of cardamom.",
    ingredients: ["Curd", "Milk", "Sugar", "Cardamom", "Rose Water", "Ice"],
    requiredIngredients: ["Curd", "Sugar"],
    optionalIngredients: ["Milk", "Cardamom", "Rose Water", "Ice"],
    prepTime: "4 mins",
    cookTime: "0 mins",
    totalMinutes: 4,
    difficulty: "Easy",
    servings: 2,
    isVegetarian: true,
    isVegan: false,
    nutrition: { calories: 180, protein: "6g", carbs: "28g", fat: "5g" },
    instructions: [
      "Whisk chilled thick yogurt with sugar, milk, and cardamom until frothy.",
      "Pour into glasses over crushed ice."
    ]
  }
];

// 24 Master Categories requested by user
const RECIPE_CATEGORIES = [
  { id: "all", name: "All Recipes", emoji: "🍽️" },
  { id: "pantry", name: "Cook With Pantry", emoji: "🍳" },
  { id: "expiring", name: "Use Soon", emoji: "🔥" },
  { id: "favorites", name: "My Favorites", emoji: "❤️" },
  { id: "breakfast", name: "Breakfast", emoji: "🍳" },
  { id: "lunch", name: "Lunch", emoji: "🍛" },
  { id: "dinner", name: "Dinner", emoji: "🍲" },
  { id: "healthy", name: "Healthy", emoji: "🥗" },
  { id: "chicken", name: "Chicken", emoji: "🍗" },
  { id: "meat", name: "Meat", emoji: "🥩" },
  { id: "fish", name: "Fish", emoji: "🐟" },
  { id: "egg", name: "Egg", emoji: "🥚" },
  { id: "vegetarian", name: "Vegetarian", emoji: "🥦" },
  { id: "vegan", name: "Vegan", emoji: "🌱" },
  { id: "pasta", name: "Pasta", emoji: "🍝" },
  { id: "rice", name: "Rice", emoji: "🍚" },
  { id: "snacks", name: "Snacks", emoji: "🥪" },
  { id: "fast-food", name: "Fast Food", emoji: "🍕" },
  { id: "desserts", name: "Desserts", emoji: "🍰" },
  { id: "drinks", name: "Drinks", emoji: "🥤" },
  { id: "indian", name: "Indian", emoji: "🍛" },
  { id: "kerala", name: "Kerala", emoji: "🇮🇳" },
  { id: "south-indian", name: "South Indian", emoji: "🇮🇳" },
  { id: "north-indian", name: "North Indian", emoji: "🇮🇳" },
  { id: "international", name: "International", emoji: "🌍" },
  { id: "quick-meals", name: "Quick Meals", emoji: "⚡" },
  { id: "budget-meals", name: "Budget Meals", emoji: "💰" },
  { id: "high-protein", name: "High Protein", emoji: "🔥" }
];

window.MASTER_RECIPES = MASTER_RECIPES;
window.RECIPE_CATEGORIES = RECIPE_CATEGORIES;
